'use client'

import { createContext, useContext, useState, type ReactNode, useEffect } from 'react'

export type Language = 'English' | 'Hindi' | 'Telugu' | 'Tamil' | 'Kannada' | 'Gujarati' | 'Malayalam' | 'Marathi' | 'Urdu'

interface LanguageContextType {
  currentLanguage: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<Language, Record<string, string>> = {
  English: {
    // Auth
    'auth.title': 'Welcome Back',
    'auth.createAccount': 'Create Account',
    'auth.signInSubtitle': 'Sign In to continue',
    'auth.signUpSubtitle': 'Sign Up to get started',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.phone': 'Phone Number',
    'auth.name': 'Full Name',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.alreadyHaveAccount': 'Already have an account?',
    
    // Role Selection
    'role.selectRole': 'Select Your Role',
    'role.jobSeeker': 'Job Seeker',
    'role.salonOwner': 'Salon Owner',
    'role.findJobs': 'Find Jobs',
    'role.manageJobs': 'Manage Jobs',
    'role.description1': 'Search and apply to salon jobs',
    'role.description2': 'Post and manage job openings',
    
    // Splash & Navigation
    'splash.poweredBy': 'Powered by Fitonze Private Limited',
    'nav.home': 'Home',
    'nav.messages': 'Messages',
    'nav.notifications': 'Notifications',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.about': 'About Us',
    
    // Job Discovery
    'job.searchJobs': 'Search jobs, salons, roles...',
    'job.filter': 'Filter',
    'job.salary': 'Salary',
    'job.experience': 'Experience',
    'job.location': 'Location',
    'job.unlock': 'Unlock',
    'job.unlockProfile': 'Unlock Profile',
    'job.message': 'Message',
    'job.apply': 'Apply Now',
    'job.saved': 'Saved',
    'job.unsave': 'Unsave',
    'job.save': 'Save',
    'job.rating': 'Rating',
    'job.reviews': 'reviews',
    'job.distance': 'km away',
    'job.accommodation': 'Accommodation',
    'job.foodProvided': 'Food Provided',
    'job.noJobs': 'No jobs found',
    'job.interested': 'Hi! I am interested in this position. I have experience in...',
    'job.areaPlaceholder': 'Enter area or city...',
    
    // Resume Builder
    'resume.buildResume': 'Build Your Resume',
    'resume.name': 'Full Name',
    'resume.role': 'Position',
    'resume.experience': 'Years of Experience',
    'resume.skills': 'Skills',
    'resume.expectedSalary': 'Expected Salary',
    'resume.location': 'Location',
    'resume.continue': 'Continue',
    'resume.next': 'Next',
    'resume.skip': 'Skip',
    
    // Subscription
    'subscription.title': 'Unlock More Features',
    'subscription.premium': 'Premium',
    'subscription.features': 'Unlimited job applications',
    'subscription.price': '₹99/month',
    'subscription.buyNow': 'Buy Now',
    'subscription.unlimitedApplications': 'Unlimited Applications',
    'subscription.priorityMatching': 'Priority Job Matching',
    'subscription.directContact': 'Direct Contact with Salons',
    
    // Job Results
    'results.applicants': 'applicants',
    'results.applications': 'Applications',
    'results.title': 'Your Applications',
    
    // Profile
    'profile.yourProfile': 'Your Profile',
    'profile.editProfile': 'Edit Profile',
    'profile.viewResume': 'View Resume',
    'profile.about': 'About',
    'profile.skills': 'Skills',
    'profile.experience': 'Experience',
    'profile.applications': 'Applications',
    'profile.saved': 'Saved Jobs',
    
    // Messages
    'messages.title': 'Messages',
    'messages.noMessages': 'No messages yet',
    'messages.typeMessage': 'Type a message...',
    'messages.send': 'Send',
    'messages.today': 'Today',
    'messages.yesterday': 'Yesterday',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.noNotifications': 'No notifications',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.clear': 'Clear all',
    
    // Settings
    'settings.title': 'Settings',
    'settings.editProfile': 'Edit Profile',
    'settings.notifications': 'Notifications',
    'settings.privacy': 'Privacy',
    'settings.help': 'Help & Support',
    'settings.language': 'Language',
    'settings.darkMode': 'Dark Mode',
    'settings.logout': 'Logout',
    'settings.jobAlerts': 'Job Alerts',
    'settings.messages': 'Messages',
    'settings.promotions': 'Promotions',
    'settings.reminders': 'Reminders',
    'settings.account': 'Account',
    'settings.preferences': 'Preferences',
    'settings.about': 'About',
    
    // About Us
    'about.title': 'About Us',
    'about.salonJobsIndia': 'Salon Jobs India',
    'about.description': 'Connecting salon professionals with opportunities',
    'about.mission': 'Our Mission',
    'about.missionText': 'To empower salon professionals and businesses through technology',
    'about.contactUs': 'Contact Us',
    'about.email': 'Email',
    'about.phone': 'Phone',
    'about.website': 'Website',
    'about.followUs': 'Follow Us',
    
    // Create Job
    'job.createJob': 'Create Job Posting',
    'job.salonName': 'Salon Name',
    'job.selectRole': 'Select Role',
    'job.customRole': 'Custom Role',
    'job.salary': 'Salary',
    'job.description': 'Job Description',
    'job.uploadLogo': 'Upload Salon Logo',
    'job.uploadScreenshot': 'Upload Payment Screenshot',
    'job.postJob': 'Post Job',
    'job.uploadImage': 'Upload Image',
    'job.fileSize': 'File size',
    'job.paymentDetails': 'Payment Details',
    'job.scanQR': 'Scan the QR code below or pay to UPI:',
    'job.payAmount': 'Pay exactly',
    'job.takeScreenshot': 'Take a screenshot of the payment confirmation',
    'job.uploadScreenshot': 'Upload the screenshot below',
    'job.confirmation': 'Confirmation',
    'job.preview': 'Preview',
    'job.postingDetails': 'Job Posting Details',
    
    // Credit Payment
    'credit.addCredits': 'Add Credits',
    'credit.currentCredits': 'Current Credits',
    'credit.buyCredits': 'Buy Credits',
    'credit.selectAmount': 'Select Amount',
    'credit.checkout': 'Checkout',
    
    // Owner Panel
    'owner.manageJobs': 'Manage Job Postings',
    'owner.activeListings': 'Active Listings',
    'owner.viewApplications': 'View Applications',
    'owner.editJob': 'Edit Job',
    'owner.deleteJob': 'Delete Job',
    'owner.unpublish': 'Unpublish',
    'owner.publish': 'Publish',
    'owner.noActiveJobs': 'No active job postings',
    'owner.createNewJob': 'Create New Job',
    
    // Salon Profile Setup
    'salon.setupProfile': 'Setup Your Salon Profile',
    'salon.salonName': 'Salon Name',
    'salon.address': 'Address',
    'salon.phone': 'Phone',
    'salon.email': 'Email',
    'salon.description': 'Description',
    'salon.uploadLogo': 'Upload Logo',
    'salon.continue': 'Continue',
    
    // General
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.remember': 'Remember',
    'common.logout': 'Logout',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
  },

  Hindi: {
    // Auth
    'auth.title': 'वापस स्वागत है',
    'auth.createAccount': 'खाता बनाएं',
    'auth.signInSubtitle': 'जारी रखने के लिए साइन इन करें',
    'auth.signUpSubtitle': 'शुरुआत करने के लिए साइन अप करें',
    'auth.signIn': 'साइन इन',
    'auth.signUp': 'साइन अप',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'auth.phone': 'फोन नंबर',
    'auth.name': 'पूरा नाम',
    'auth.forgotPassword': 'पासवर्ड भूल गए?',
    'auth.dontHaveAccount': 'खाता नहीं है?',
    'auth.alreadyHaveAccount': 'पहले से ही खाता है?',
    
    // Role Selection
    'role.selectRole': 'अपनी भूमिका चुनें',
    'role.jobSeeker': 'नौकरी तलाशने वाला',
    'role.salonOwner': 'सैलून मालिक',
    'role.findJobs': 'नौकरियां खोजें',
    'role.manageJobs': 'नौकरियों का प्रबंधन करें',
    'role.description1': 'सैलून की नौकरियों को खोजें और आवेदन करें',
    'role.description2': 'नौकरी की खुलीखेजों को पोस्ट और प्रबंधित करें',
    
    // Splash & Navigation
    'splash.poweredBy': 'Fitonze प्राइवेट लिमिटेड द्वारा संचालित',
    'nav.home': 'होम',
    'nav.messages': 'संदेश',
    'nav.notifications': 'सूचनाएं',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.settings': 'सेटिंग्स',
    'nav.about': 'हमारे बारे में',
    
    // Job Discovery
    'job.searchJobs': 'नौकरियों, सैलूनों, भूमिकाओं को खोजें...',
    'job.filter': 'फ़िल्टर',
    'job.salary': 'वेतन',
    'job.experience': 'अनुभव',
    'job.location': 'स्थान',
    'job.unlock': 'अनलॉक करें',
    'job.unlockProfile': 'प्रोफ़ाइल अनलॉक करें',
    'job.message': 'संदेश',
    'job.apply': 'अभी आवेदन करें',
    'job.saved': 'सहेजे गए',
    'job.unsave': 'अनसेव करें',
    'job.save': 'सहेजें',
    'job.rating': 'रेटिंग',
    'job.reviews': 'समीक्षाएं',
    'job.distance': 'किमी दूर',
    'job.accommodation': 'आवास',
    'job.foodProvided': 'भोजन प्रदान किया गया',
    'job.noJobs': 'कोई नौकरी नहीं मिली',
    'job.interested': 'नमस्ते! मुझे इस पद में रुचि है। मेरे पास अनुभव है...',
    'job.areaPlaceholder': 'क्षेत्र या शहर दर्ज करें...',
    
    // Resume Builder
    'resume.buildResume': 'अपना रिज्यूमे बनाएं',
    'resume.name': 'पूरा नाम',
    'resume.role': 'पद',
    'resume.experience': 'वर्षों का अनुभव',
    'resume.skills': 'कौशल',
    'resume.expectedSalary': 'अपेक्षित वेतन',
    'resume.location': 'स्थान',
    'resume.continue': 'जारी रखें',
    'resume.next': 'आगे',
    'resume.skip': 'छोड़ें',
    
    // Subscription
    'subscription.title': 'अधिक सुविधाओं को अनलॉक करें',
    'subscription.premium': 'प्रीमियम',
    'subscription.features': 'असीमित नौकरी आवेदन',
    'subscription.price': '₹99/माह',
    'subscription.buyNow': 'अभी खरीदें',
    'subscription.unlimitedApplications': 'असीमित आवेदन',
    'subscription.priorityMatching': 'प्राथमिकता नौकरी मिलान',
    'subscription.directContact': 'सैलूनों के साथ सीधा संपर्क',
    
    // Job Results
    'results.applicants': 'आवेदक',
    'results.applications': 'आवेदन',
    'results.title': 'आपके आवेदन',
    
    // Profile
    'profile.yourProfile': 'आपकी प्रोफ़ाइल',
    'profile.editProfile': 'प्रोफ़ाइल संपादित करें',
    'profile.viewResume': 'रिज्यूमे देखें',
    'profile.about': 'परिचय',
    'profile.skills': 'कौशल',
    'profile.experience': 'अनुभव',
    'profile.applications': 'आवेदन',
    'profile.saved': 'सहेजी गई नौकरियां',
    
    // Messages
    'messages.title': 'संदेश',
    'messages.noMessages': 'अभी तक कोई संदेश नहीं',
    'messages.typeMessage': 'एक संदेश टाइप करें...',
    'messages.send': 'भेजें',
    'messages.today': 'आज',
    'messages.yesterday': 'कल',
    
    // Notifications
    'notifications.title': 'सूचनाएं',
    'notifications.noNotifications': 'कोई सूचना नहीं',
    'notifications.markAllRead': 'सभी को पढ़ा हुआ चिन्हित करें',
    'notifications.clear': 'सभी साफ़ करें',
    
    // Settings
    'settings.title': 'सेटिंग्स',
    'settings.editProfile': 'प्रोफ़ाइल संपादित करें',
    'settings.notifications': 'सूचनाएं',
    'settings.privacy': 'गोपनीयता',
    'settings.help': 'सहायता और समर्थन',
    'settings.language': 'भाषा',
    'settings.darkMode': 'डार्क मोड',
    'settings.logout': 'लॉग आउट',
    'settings.jobAlerts': 'नौकरी सतर्कताएं',
    'settings.messages': 'संदेश',
    'settings.promotions': 'प्रचार',
    'settings.reminders': 'याद दिलाएं',
    'settings.account': 'खाता',
    'settings.preferences': 'प्राथमिकताएं',
    'settings.about': 'हमारे बारे में',
    
    // About Us
    'about.title': 'हमारे बारे में',
    'about.salonJobsIndia': 'सैलून जॉब्स इंडिया',
    'about.description': 'सैलून पेशेवरों को अवसरों से जोड़ना',
    'about.mission': 'हमारा मिशन',
    'about.missionText': 'सैलून पेशेवरों और व्यवसायों को प्रौद्योगिकी के माध्यम से सशक्त करना',
    'about.contactUs': 'हमसे संपर्क करें',
    'about.email': 'ईमेल',
    'about.phone': 'फोन',
    'about.website': 'वेबसाइट',
    'about.followUs': 'हमें फॉलो करें',
    
    // Create Job
    'job.createJob': 'नौकरी पोस्टिंग बनाएं',
    'job.salonName': 'सैलून का नाम',
    'job.selectRole': 'भूमिका चुनें',
    'job.customRole': 'कस्टम भूमिका',
    'job.salary': 'वेतन',
    'job.description': 'नौकरी का विवरण',
    'job.uploadLogo': 'सैलून लोगो अपलोड करें',
    'job.uploadScreenshot': 'भुगतान स्क्रीनशॉट अपलोड करें',
    'job.postJob': 'नौकरी पोस्ट करें',
    'job.uploadImage': 'छवि अपलोड करें',
    'job.fileSize': 'फ़ाइल आकार',
    'job.paymentDetails': 'भुगतान विवरण',
    'job.scanQR': 'नीचे दिए गए QR कोड को स्कैन करें या UPI को भुगतान करें:',
    'job.payAmount': 'बिल्कुल भुगतान करें',
    'job.takeScreenshot': 'भुगतान की पुष्टि का एक स्क्रीनशॉट लें',
    'job.uploadScreenshot': 'नीचे स्क्रीनशॉट अपलोड करें',
    'job.confirmation': 'पुष्टि',
    'job.preview': 'पूर्वावलोकन',
    'job.postingDetails': 'नौकरी पोस्टिंग विवरण',
    
    // Credit Payment
    'credit.addCredits': 'क्रेडिट जोड़ें',
    'credit.currentCredits': 'वर्तमान क्रेडिट',
    'credit.buyCredits': 'क्रेडिट खरीदें',
    'credit.selectAmount': 'राशि चुनें',
    'credit.checkout': 'चेकआउट',
    
    // Owner Panel
    'owner.manageJobs': 'नौकरी पोस्टिंग प्रबंधित करें',
    'owner.activeListings': 'सक्रिय सूचियां',
    'owner.viewApplications': 'आवेदन देखें',
    'owner.editJob': 'नौकरी संपादित करें',
    'owner.deleteJob': 'नौकरी हटाएं',
    'owner.unpublish': 'अप्रकाशित करें',
    'owner.publish': 'प्रकाशित करें',
    'owner.noActiveJobs': 'कोई सक्रिय नौकरी पोस्टिंग नहीं',
    'owner.createNewJob': 'नई नौकरी बनाएं',
    
    // Salon Profile Setup
    'salon.setupProfile': 'अपनी सैलून प्रोफ़ाइल सेट करें',
    'salon.salonName': 'सैलून का नाम',
    'salon.address': 'पता',
    'salon.phone': 'फोन',
    'salon.email': 'ईमेल',
    'salon.description': 'विवरण',
    'salon.uploadLogo': 'लोगो अपलोड करें',
    'salon.continue': 'जारी रखें',
    
    // General
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.delete': 'हटाएं',
    'common.edit': 'संपादित करें',
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.success': 'सफलता',
    'common.back': 'वापस',
    'common.next': 'आगे',
    'common.remember': 'याद रखें',
    'common.logout': 'लॉग आउट',
    'common.confirm': 'पुष्टि करें',
    'common.yes': 'हाँ',
    'common.no': 'नहीं',
  },

  Telugu: {
    // Auth
    'auth.title': 'తిరిగి స్వాగతం',
    'auth.createAccount': 'ఖాతా సృష్టించండి',
    'auth.signInSubtitle': 'కొనసాగించడానికి సైన్ ఇన్ చేయండి',
    'auth.signUpSubtitle': 'ప్రారంభించడానికి సైన్ అప్ చేయండి',
    'auth.signIn': 'సైన్ ఇన్ చేయి',
    'auth.signUp': 'సైన్ అప్ చేయి',
    'auth.email': 'ఇమెయిల్',
    'auth.password': 'పాస్‌వర్డ్',
    'auth.phone': 'ఫోన్ నంబర్',
    'auth.name': 'పూర్తి పేరు',
    'auth.forgotPassword': 'పాస్‌వర్డ్ మరిచిపోయారా?',
    'auth.dontHaveAccount': 'ఖాతా లేదు?',
    'auth.alreadyHaveAccount': 'ఇప్పటికే ఖాతా ఉందా?',
    
    // Role Selection
    'role.selectRole': 'మీ పాత్రను ఎంచుకోండి',
    'role.jobSeeker': 'ఉద్యోగ చేవరు',
    'role.salonOwner': 'సెలూన్ యజమాని',
    'role.findJobs': 'ఉద్యోగాలను కనుగొనండి',
    'role.manageJobs': 'ఉద్యోగాలను నిర్వహించండి',
    'role.description1': 'సెలూన్ ఉద్యోగాలను శోధించండి మరియు దరఖాస్తు చేయండి',
    'role.description2': 'ఉద్యోగ ఖాళీలను పోస్ట్ చేయండి మరియు నిర్వహించండి',
    
    // Splash & Navigation
    'splash.poweredBy': 'Fitonze ప్రైవేట్ లిమిటెడ్ ద్వారా ఆధారితం',
    'nav.home': 'హోమ్',
    'nav.messages': 'సందేశాలు',
    'nav.notifications': 'నోటిఫికేషన్‌లు',
    'nav.profile': 'ప్రొఫైల్',
    'nav.settings': 'సెట్టింగ్‌లు',
    'nav.about': 'మమ్మల్నీ గురించి',
    
    // Job Discovery
    'job.searchJobs': 'ఉద్యోగాలు, సెలూన్‌లు, పాత్రలను శోధించండి...',
    'job.filter': 'ఫిల్టర్ చేయి',
    'job.salary': 'జీతం',
    'job.experience': 'అనుభవం',
    'job.location': 'ప్రదేశం',
    'job.unlock': 'అన్‌లాక్ చేయండి',
    'job.unlockProfile': 'ప్రొఫైల్‌ను అన్‌లాక్ చేయండి',
    'job.message': 'సందేశం',
    'job.apply': 'ఇప్పుడు దరఖాస్తు చేయండి',
    'job.saved': 'సేవ్ చేసిన',
    'job.unsave': 'సేవ్‌ను తీసివేయండి',
    'job.save': 'సేవ్ చేయండి',
    'job.rating': 'రేటింగ్',
    'job.reviews': 'సమీక్షలు',
    'job.distance': 'కిమీ దూరం',
    'job.accommodation': 'వసతులు',
    'job.foodProvided': 'ఆహారం అందించబడుతుంది',
    'job.noJobs': 'ఉద్యోగాలు కనుగొనబడలేదు',
    'job.interested': 'హాయ్! ఈ పद గురించి నాకు ఆసక్తి ఉంది. నాకు అనుభవం ఉంది...',
    'job.areaPlaceholder': 'ప్రాంతం లేదా నగరాన్ని నమోదు చేయండి...',
    
    // Resume Builder
    'resume.buildResume': 'మీ రిజ్యూమ్‌ను రూపొందించండి',
    'resume.name': 'పూర్తి పేరు',
    'resume.role': 'పదం',
    'resume.experience': 'సంవత్సరాల అనుభవం',
    'resume.skills': 'నైపుణ్యాలు',
    'resume.expectedSalary': 'ఆశించిన జీతం',
    'resume.location': 'ప్రదేశం',
    'resume.continue': 'కొనసాగించండి',
    'resume.next': 'తరువాత',
    'resume.skip': 'దాటవేయండి',
    
    // Subscription
    'subscription.title': 'మరిన్ని ఫీచర్‌లను అన్‌లాక్ చేయండి',
    'subscription.premium': 'ప్రీమియం',
    'subscription.features': 'అపరిమిత ఉద్యోగ దరఖాస్తులు',
    'subscription.price': '₹99/నెల',
    'subscription.buyNow': 'ఇప్పుడు కొనండి',
    'subscription.unlimitedApplications': 'అపరిమిత దరఖాస్తులు',
    'subscription.priorityMatching': 'ప్రాధాన్యత ఉద్యోగ సరిపోలిక',
    'subscription.directContact': 'సెలూన్‌లతో నేరుగా సంపర్కం',
    
    // Job Results
    'results.applicants': 'దరఖాస్తుదారులు',
    'results.applications': 'దరఖాస్తులు',
    'results.title': 'మీ దరఖాస్తులు',
    
    // Profile
    'profile.yourProfile': 'మీ ప్రొఫైల్',
    'profile.editProfile': 'ప్రొఫైల్‌ను సవరించండి',
    'profile.viewResume': 'రిజ్యూమ్‌ను చూడండి',
    'profile.about': 'గురించి',
    'profile.skills': 'నైపుణ్యాలు',
    'profile.experience': 'అనుభవం',
    'profile.applications': 'దరఖాస్తులు',
    'profile.saved': 'సేవ్ చేసిన ఉద్యోగాలు',
    
    // Messages
    'messages.title': 'సందేశాలు',
    'messages.noMessages': 'ఇంకా సందేశాలు లేవు',
    'messages.typeMessage': 'సందేశం టైప్ చేయండి...',
    'messages.send': 'పంపించు',
    'messages.today': 'ఈ రోజు',
    'messages.yesterday': 'నిన్న',
    
    // Notifications
    'notifications.title': 'నోటిఫికేషన్‌లు',
    'notifications.noNotifications': 'నోటిఫికేషన్‌లు లేవు',
    'notifications.markAllRead': 'అన్నింటిని చదవబడినట్లు గుర్తించండి',
    'notifications.clear': 'అన్నీ క్లియర్ చేయండి',
    
    // Settings
    'settings.title': 'సెట్టింగ్‌లు',
    'settings.editProfile': 'ప్రొఫైల్‌ను సవరించండి',
    'settings.notifications': 'నోటిఫికేషన్‌లు',
    'settings.privacy': 'ఆస్తిత్వం',
    'settings.help': 'సహాయం & సపోర్టు',
    'settings.language': 'భాష',
    'settings.darkMode': 'చీకటి విధానం',
    'settings.logout': 'లాగ్ అవుట్',
    'settings.jobAlerts': 'ఉద్యోగ హెచ్చరికలు',
    'settings.messages': 'సందేశాలు',
    'settings.promotions': 'ప్రమోషన్‌లు',
    'settings.reminders': 'రిమైండర్‌లు',
    'settings.account': 'ఖాతా',
    'settings.preferences': 'ప్రాధాన్యతలు',
    'settings.about': 'గురించి',
    
    // About Us
    'about.title': 'మమ్మల్నీ గురించి',
    'about.salonJobsIndia': 'సెలూన్ జాబ్‌లు ఇండియా',
    'about.description': 'సెలూన్ నిపుణులను అవకాశాలకు కనెక్ట్ చేయండి',
    'about.mission': 'మా లక్ష్యం',
    'about.missionText': 'సెలూన్ నిపుణులు మరియు వ్యవసాయాలను సాంకేతికత ద్వారా ఆధికారపరచండి',
    'about.contactUs': 'మాకు సంపర్కించండి',
    'about.email': 'ఇమెయిల్',
    'about.phone': 'ఫోన్',
    'about.website': 'వెబ్‌సైట్',
    'about.followUs': 'మమ్మల్ని అనుసరించండి',
    
    // Create Job
    'job.createJob': 'ఉద్యోగ పోస్టింగ్‌ను సృష్టించండి',
    'job.salonName': 'సెలూన్ పేరు',
    'job.selectRole': 'పాత్ర ఎంచుకోండి',
    'job.customRole': 'కస్టమ్ రోల్',
    'job.salary': 'జీతం',
    'job.description': 'ఉద్యోగ వివరణ',
    'job.uploadLogo': 'సెలూన్ లోగో అప్‌లోడ్ చేయండి',
    'job.uploadScreenshot': 'చెల్లింపు స్క్రీన్‌షాట్ అప్‌లోడ్ చేయండి',
    'job.postJob': 'ఉద్యోగం పోస్ట్ చేయండి',
    'job.uploadImage': 'ఇమేజ్ అప్‌లోడ్ చేయండి',
    'job.fileSize': 'ఫైల్ సైజ్',
    'job.paymentDetails': 'చెల్లింపు వివరాలు',
    'job.scanQR': 'దిగువ QR కోడ్‌ను స్కాన్ చేయండి లేదా UPI కు చెల్లించండి:',
    'job.payAmount': 'ఖచ్చితంగా చెల్లించండి',
    'job.takeScreenshot': 'చెల్లింపు నిర్ధారణ యొక్క స్క్రీన్‌షాట్‌ను తీయండి',
    'job.uploadScreenshot': 'దిగువ స్క్రీన్‌షాట్‌ను అప్‌లోడ్ చేయండి',
    'job.confirmation': 'నిర్ధారణ',
    'job.preview': 'ప్రిజ్యూ',
    'job.postingDetails': 'ఉద్యోగ పోస్టింగ్ వివరాలు',
    
    // Credit Payment
    'credit.addCredits': 'క్రెడిట్‌లను జోడించండి',
    'credit.currentCredits': 'ప్రస్తుత క్రెడిట్‌లు',
    'credit.buyCredits': 'క్రెడిట్‌లను కొనండి',
    'credit.selectAmount': 'మొత్తాన్ని ఎంచుకోండి',
    'credit.checkout': 'చెక్‌అవుట్',
    
    // Owner Panel
    'owner.manageJobs': 'ఉద్యోగ పోస్టింగ్‌లను నిర్వహించండి',
    'owner.activeListings': 'క్రియాశీల జాబితాలు',
    'owner.viewApplications': 'దరఖాస్తులను చూడండి',
    'owner.editJob': 'ఉద్యోగాన్ని సవరించండి',
    'owner.deleteJob': 'ఉద్యోగాన్ని తొలగించండి',
    'owner.unpublish': 'ప్రచురణ చేయవద్దు',
    'owner.publish': 'ప్రచురించండి',
    'owner.noActiveJobs': 'క్రియాశీల ఉద్యోగ పోస్టింగ్ లేదు',
    'owner.createNewJob': 'కొత్త ఉద్యోగాన్ని సృష్టించండి',
    
    // Salon Profile Setup
    'salon.setupProfile': 'మీ సెలూన్ ప్రొఫైల్‌ను సెట్ చేయండి',
    'salon.salonName': 'సెలూన్ పేరు',
    'salon.address': 'చిరునామా',
    'salon.phone': 'ఫోన్',
    'salon.email': 'ఇమెయిల్',
    'salon.description': 'వివరణ',
    'salon.uploadLogo': 'లోగో అప్‌లోడ్ చేయండి',
    'salon.continue': 'కొనసాగించండి',
    
    // General
    'common.save': 'సేవ్ చేయండి',
    'common.cancel': 'రద్దు చేయండి',
    'common.delete': 'తొలగించండి',
    'common.edit': 'సవరించండి',
    'common.loading': 'లోడ్ చేస్తోంది...',
    'common.error': 'లోపం',
    'common.success': 'సఫలం',
    'common.back': 'వెనుకకు',
    'common.next': 'తరువాత',
    'common.remember': 'గుర్తుంచుకోండి',
    'common.logout': 'లాగ్ అవుట్',
    'common.confirm': 'నిర్ధారించండి',
    'common.yes': 'అవును',
    'common.no': 'లేదు',
  },

  Tamil: {
    // Auth
    'auth.title': 'மீண்டும் வரவேற்கிறோம்',
    'auth.createAccount': 'கணக்கு உருவாக்கவும்',
    'auth.signInSubtitle': 'தொடர சைன் இன் செய்யவும்',
    'auth.signUpSubtitle': 'தொடங்க சைன் அப் செய்யவும்',
    'auth.signIn': 'சைன் இன்',
    'auth.signUp': 'சைன் அப்',
    'auth.email': 'ஈமெயில்',
    'auth.password': 'கடவுசொல்',
    'auth.phone': 'ফোன் எண்',
    'auth.name': 'முழு பெயர்',
    'auth.forgotPassword': 'கடவுசொல் மறந்துவிட்டீர்களா?',
    'auth.dontHaveAccount': 'கணக்கு இல்லையா?',
    'auth.alreadyHaveAccount': 'ஏற்கனவே கணக்கு உள்ளதா?',
    
    // Role Selection
    'role.selectRole': 'உங்கள் பாத்திரத்தைத் தேர்ந்தெடுக்கவும்',
    'role.jobSeeker': 'வேலை தேடுபவர்',
    'role.salonOwner': 'சலூன் உரிமையாளர்',
    'role.findJobs': 'வேலைகளைக் கண்டுபிடிக்கவும்',
    'role.manageJobs': 'வேலைகளை நிர்வகிக்கவும்',
    'role.description1': 'சலூன் வேலைகளைத் தேடுங்கள் மற்றும் விண்ணப்பிக்கவும்',
    'role.description2': 'வேலையின் இடங்களை பிரকাசிக்கவும் மற்றும் நிர்வகிக்கவும்',
    
    // Splash & Navigation
    'splash.poweredBy': 'Fitonze Private Limited மூலம் இயக்கப்படும்',
    'nav.home': 'வீடு',
    'nav.messages': 'செய்திகள்',
    'nav.notifications': 'அறிவிப்புக்கள்',
    'nav.profile': 'சுயவிவரம்',
    'nav.settings': 'அமைப்புகள்',
    'nav.about': 'எங்களைப் பற்றி',
    
    // Job Discovery
    'job.searchJobs': 'வேலைகள், சலூன்கள், பாத்திரங்களை தேடுங்கள்...',
    'job.filter': 'வடிப்பி',
    'job.salary': 'சம்பளம்',
    'job.experience': 'அனுபவம்',
    'job.location': 'இடம்',
    'job.unlock': 'திறக்கவும்',
    'job.unlockProfile': 'சுயவிவரத்தை திறக்கவும்',
    'job.message': 'செய்தி',
    'job.apply': 'இப்போது விண்ணப்பிக்கவும்',
    'job.saved': 'சேமிக்கப்பட்டவை',
    'job.unsave': 'சேமிப்பை மீட்க',
    'job.save': 'சேமி',
    'job.rating': 'மதிப்பீடு',
    'job.reviews': 'விமர்சனங்கள்',
    'job.distance': 'கி.மீ தூரம்',
    'job.accommodation': 'தங்குமிடம்',
    'job.foodProvided': 'உணவு வழங்கப்பட்டுள்ளது',
    'job.noJobs': 'வேலைகள் கண்டுபிடிக்கப்படவில்லை',
    'job.interested': 'வணக்கம்! இந்த வேலை எனக்கு ஆர்வமாக உள்ளது. என்னிடம் அனுபவம் உள்ளது...',
    'job.areaPlaceholder': 'பகுதி அல்லது நகரத்தை உள்ளிடவும்...',
    
    // Resume Builder
    'resume.buildResume': 'உங்கள் மீண்டும் கட்டமைக்கவும்',
    'resume.name': 'முழு பெயர்',
    'resume.role': 'நிலை',
    'resume.experience': 'ஆண்டுகளின் அனுபவம்',
    'resume.skills': 'திறன்கள்',
    'resume.expectedSalary': 'எதிர்பார்க்கப்பட்ட சம்பளம்',
    'resume.location': 'இடம்',
    'resume.continue': 'தொடரவும்',
    'resume.next': 'அடுத்து',
    'resume.skip': 'தவிர்க்கவும்',
    
    // Subscription
    'subscription.title': 'மேலும் அம்சங்களை திறக்கவும்',
    'subscription.premium': 'பிரீமியம்',
    'subscription.features': 'எல்லையற்ற வேலை விண்ணப்பங்கள்',
    'subscription.price': '₹99/மாதம்',
    'subscription.buyNow': 'இப்போது வாங்கவும்',
    'subscription.unlimitedApplications': 'எல்லையற்ற விண்ணப்பங்கள்',
    'subscription.priorityMatching': 'முன்னுரிமை வேலை பொருத்தம்',
    'subscription.directContact': 'சலூன்களுடனான நேரடி தொடர்பு',
    
    // Job Results
    'results.applicants': 'விண்ணப்பதாரர்கள்',
    'results.applications': 'விண்ணப்பங்கள்',
    'results.title': 'உங்கள் விண்ணப்பங்கள்',
    
    // Profile
    'profile.yourProfile': 'உங்கள் சுயவிவரம்',
    'profile.editProfile': 'சுயவிவரத்தை திருத்தவும்',
    'profile.viewResume': 'மீண்டும் பார்க்கவும்',
    'profile.about': 'பற்றி',
    'profile.skills': 'திறன்கள்',
    'profile.experience': 'அனுபவம்',
    'profile.applications': 'விண்ணப்பங்கள்',
    'profile.saved': 'சேமிக்கப்பட்ட வேலைகள்',
    
    // Messages
    'messages.title': 'செய்திகள்',
    'messages.noMessages': 'இன்னும் செய்திகளைப் பெறவில்லை',
    'messages.typeMessage': 'ஒரு செய்தியை தட்டச்சு செய்யவும்...',
    'messages.send': 'அனுப்பவும்',
    'messages.today': 'இன்று',
    'messages.yesterday': 'நேற்று',
    
    // Notifications
    'notifications.title': 'அறிவிப்புக்கள்',
    'notifications.noNotifications': 'அறிவிப்புக்கள் இல்லை',
    'notifications.markAllRead': 'அனைத்தையும் படித்தது என குறிப்பிடவும்',
    'notifications.clear': 'அனைத்தையும் அழிக்கவும்',
    
    // Settings
    'settings.title': 'அமைப்புகள்',
    'settings.editProfile': 'சுயவிவரத்தை திருத்தவும்',
    'settings.notifications': 'அறிவிப்புக்கள்',
    'settings.privacy': 'தனியுரிமை',
    'settings.help': 'உதவி மற்றும் ஆதரவு',
    'settings.language': 'மொழி',
    'settings.darkMode': 'இருண்ட பயன்முறை',
    'settings.logout': 'வெளியேறு',
    'settings.jobAlerts': 'வேலை எச்சரிக்கைகள்',
    'settings.messages': 'செய்திகள்',
    'settings.promotions': 'பதவி உயர்வு',
    'settings.reminders': 'நினைவூட்டல்கள்',
    'settings.account': 'கணக்கு',
    'settings.preferences': 'விருப்பத்தேர்வுகள்',
    'settings.about': 'பற்றி',
    
    // About Us
    'about.title': 'எங்களைப் பற்றி',
    'about.salonJobsIndia': 'சலூன் வேலைகள் இந்தியா',
    'about.description': 'சலூன் தொழில்முறைகளை வாய்ப்புகளுடன் இணைக்கவும்',
    'about.mission': 'எங்கள் பணி',
    'about.missionText': 'சலூன் தொழில்முறைகள் மற்றும் ব்যবसाக்களை தொழில்நுட்பத்தின் மூலம் அதिकாரமயப்படுத்துக',
    'about.contactUs': 'எங்களைத் தொடர்பு கொள்ளவும்',
    'about.email': 'ஈமெயில்',
    'about.phone': 'ফোன்',
    'about.website': 'வலைத்தளம்',
    'about.followUs': 'ஆம்ப் ஐ பின்தொடரவும்',
    
    // Create Job
    'job.createJob': 'வேலை பிரকாசனம் உருவாக்கவும்',
    'job.salonName': 'சலூன் பெயர்',
    'job.selectRole': 'பாத்திரத்தைத் தேர்ந்தெடுக்கவும்',
    'job.customRole': 'தனிப்பயன் பாத்திரம்',
    'job.salary': 'சம்பளம்',
    'job.description': 'வேலையின் விளக்கம்',
    'job.uploadLogo': 'சலூன் லோகோ பதிவேற்றவும்',
    'job.uploadScreenshot': 'பேமেंट் ஸ்क्रीनशॉट் பதிவேற்றவும்',
    'job.postJob': 'வேலை வெளியிடவும்',
    'job.uploadImage': 'ছवि पढ़ाएं',
    'job.fileSize': 'ফাইল আकार',
    'job.paymentDetails': 'பেमेंट विवरण',
    'job.scanQR': 'नीचे दिए गए QR कोड को स्कैन करें या UPI को भुगतान करें:',
    'job.payAmount': 'बिल्कुल भुगतान करें',
    'job.takeScreenshot': 'पेमेंट की पुष्टि का एक स्क्रीनशॉट लें',
    'job.uploadScreenshot': 'नीचे स्क्रीनशॉट अपलोड करें',
    'job.confirmation': 'पुष्टि',
    'job.preview': 'पूर्वावलोकन',
    'job.postingDetails': 'वेतन पोस्टिंग विवरण',
    
    // Credit Payment
    'credit.addCredits': 'க्रेडिट जोड़ें',
    'credit.currentCredits': 'वर्तमान क्रेडिट',
    'credit.buyCredits': 'क्रेडिट खरीदें',
    'credit.selectAmount': 'राशि चुनें',
    'credit.checkout': 'चेकआउट',
    
    // Owner Panel
    'owner.manageJobs': 'वेतन पोस्टिंग प्रबंधित करें',
    'owner.activeListings': 'सक्रिय सूचियां',
    'owner.viewApplications': 'आवेदन देखें',
    'owner.editJob': 'वेतन संपादित करें',
    'owner.deleteJob': 'वेतन हटाएं',
    'owner.unpublish': 'अप्रकाशित करें',
    'owner.publish': 'प्रकाशित करें',
    'owner.noActiveJobs': 'कोई सक्रिय वेतन पोस्टिंग नहीं',
    'owner.createNewJob': 'नई वेतन बनाएं',
    
    // Salon Profile Setup
    'salon.setupProfile': 'अपनी सलून प्रोफाइल सेट करें',
    'salon.salonName': 'सलून का नाम',
    'salon.address': 'पता',
    'salon.phone': 'फोन',
    'salon.email': 'ईमेल',
    'salon.description': 'विवरण',
    'salon.uploadLogo': 'लोगो अपलोड करें',
    'salon.continue': 'जारी रखें',
    
    // General
    'common.save': 'सेव करें',
    'common.cancel': 'रद्द करें',
    'common.delete': 'हटाएं',
    'common.edit': 'संपादित करें',
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.success': 'सफलता',
    'common.back': 'वापस',
    'common.next': 'अगला',
    'common.remember': 'याद रखें',
    'common.logout': 'लॉग आउट',
    'common.confirm': 'पुष्टि करें',
    'common.yes': 'हां',
    'common.no': 'नहीं',
  },

  Kannada: {
    // Auth
    'auth.title': 'ಮತ್ತೆ ಸ್ವಾಗತ',
    'auth.createAccount': 'ಖಾತೆ ರಚಿಸಿ',
    'auth.signInSubtitle': 'ಮುಂದುವರೆಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ',
    'auth.signUpSubtitle': 'ಪ್ರಾರಂಭಿಸಲು ಸೈನ್ ಅಪ್ ಮಾಡಿ',
    'auth.signIn': 'ಸೈನ್ ಇನ್ ಮಾಡಿ',
    'auth.signUp': 'ಸೈನ್ ಅಪ್ ಮಾಡಿ',
    'auth.email': 'ಇಮೇಲ್',
    'auth.password': 'ಪಾಸ್‌ವರ್ಡ್',
    'auth.phone': 'ಫೋನ್ ಸಂಖ್ಯೆ',
    'auth.name': 'ಪೂರ್ಣ ಹೆಸರು',
    'auth.forgotPassword': 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತುಬಿದ್ದೀರಾ?',
    'auth.dontHaveAccount': 'ಖಾತೆ ಇಲ್ಲವೇ?',
    'auth.alreadyHaveAccount': 'ಈಗಾಗಲೆ ಖಾತೆ ಇದೆಯೇ?',
    
    // Role Selection
    'role.selectRole': 'ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆರಿಸಿ',
    'role.jobSeeker': 'ಕೆಲಸ ಹುಡುಕುವವರು',
    'role.salonOwner': 'ಸ್ಯಾಲೂನ್ ಮಾಲಿಕ',
    'role.findJobs': 'ಕೆಲಸಗಳನ್ನು ಹುಡುಕಿ',
    'role.manageJobs': 'ಕೆಲಸಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    'role.description1': 'ಸ್ಯಾಲೂನ್ ಕೆಲಸಗಳನ್ನು ಹುಡುಕಿ ಮತ್ತು ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    'role.description2': 'ಕೆಲಸದ ತೆರೆಯುಕೆಗಳನ್ನು ಪೋಸ್ಟ್ ಮಾಡಿ ಮತ್ತು ನಿರ್ವಹಿಸಿ',
    
    // Splash & Navigation
    'splash.poweredBy': 'Fitonze ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್ ನಿಂದ ಚಾಲಿತ',
    'nav.home': 'ಮುಖ್ಯ ಪುಟ',
    'nav.messages': 'ಸಂದೇಶಗಳು',
    'nav.notifications': 'ಸೂಚನೆಗಳು',
    'nav.profile': 'ಪ್ರೊಫೈಲ್',
    'nav.settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'nav.about': 'ನಮ್ಮ ಬಗ್ಗೆ',
    
    // Job Discovery
    'job.searchJobs': 'ಕೆಲಸಗಳು, ಸ್ಯಾಲೂನ್‌ಗಳು, ಪಾತ್ರಗಳನ್ನು ಹುಡುಕಿ...',
    'job.filter': 'ಫಿಲ್ಟರ್',
    'job.salary': 'ಸಂಬಳ',
    'job.experience': 'ಅನುಭವ',
    'job.location': 'ಸ್ಥಾನ',
    'job.unlock': 'ಅನ್‌ಲಾಕ್ ಮಾಡಿ',
    'job.unlockProfile': 'ಪ್ರೊಫೈಲ್ ಅನ್‌ಲಾಕ್ ಮಾಡಿ',
    'job.message': 'ಸಂದೇಶ',
    'job.apply': 'ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    'job.saved': 'ಸಂರಕ್ಷಿತ',
    'job.unsave': 'ಸಂರಕ್ಷಣೆ ತೆಗೆದುಹಾಕಿ',
    'job.save': 'ಸಂರಕ್ಷಿಸಿ',
    'job.rating': 'ರೇಟಿಂಗ್',
    'job.reviews': 'ವಿಮರ್ಶೆಗಳು',
    'job.distance': 'ಕಿ.ಮೀ ದೂರ',
    'job.accommodation': 'ಆವಾಸ',
    'job.foodProvided': 'ಭೋಜನ ಒದಗಿಸಲಾಗಿದೆ',
    'job.noJobs': 'ಕೆಲಸಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    'job.interested': 'ಹಾಯ್! ಈ ಸ್ಥಾನದಲ್ಲಿ ನನಗೆ ಆಸಕ್ತಿ ಇದೆ. ನನ್ನಕ್ಕೆ ಅನುಭವ ಇದೆ...',
    'job.areaPlaceholder': 'ಪ್ರದೇಶ ಅಥವಾ ನಗರವನ್ನು ನಮೂದಿಸಿ...',
    
    // Resume Builder
    'resume.buildResume': 'ನಿಮ್ಮ ರಿಜ್ಯೂಮೆ ನಿರ್ಮಿಸಿ',
    'resume.name': 'ಪೂರ್ಣ ಹೆಸರು',
    'resume.role': 'ಸ್ಥಾನ',
    'resume.experience': 'ವರ್ಷಗಳ ಅನುಭವ',
    'resume.skills': 'ಕೌಶಲ್ಯಗಳು',
    'resume.expectedSalary': 'ನಿರೀಕ್ಷಿತ ಸಂಬಳ',
    'resume.location': 'ಸ್ಥಾನ',
    'resume.continue': 'ಮುಂದುವರೆಯಿರಿ',
    'resume.next': 'ಮುಂದೆ',
    'resume.skip': 'ಬಿಟ್ಟುಬಿಡಿ',
    
    // Subscription
    'subscription.title': 'ಹೆಚ್ಚಿನ ವೈಶಿಷ್ಟ್ಯಗಳನ್ನು ಅನ್‌ಲಾಕ್ ಮಾಡಿ',
    'subscription.premium': 'ಪ್ರೀಮಿಯಮ್',
    'subscription.features': 'ಅಸೀಮಿತ ಕೆಲಸ ಅರ್ಜಿಗಳು',
    'subscription.price': '₹99/ತಿಂಗಳು',
    'subscription.buyNow': 'ಈಗ ಖರೀದಿಸಿ',
    'subscription.unlimitedApplications': 'ಅಸೀಮಿತ ಅರ್ಜಿಗಳು',
    'subscription.priorityMatching': 'ಆದ್ಯತೆ ಕೆಲಸ ಹೊಂದಾಣಿಕೆ',
    'subscription.directContact': 'ಸ್ಯಾಲೂನ್‌ಗಳೊಂದಿಗೆ ನೇರ ಸಂಪರ್ಕ',
    
    // Job Results
    'results.applicants': 'ಅರ್ಹತೆದಾರರು',
    'results.applications': 'ಅರ್ಜಿಗಳು',
    'results.title': 'ನಿಮ್ಮ ಅರ್ಜಿಗಳು',
    
    // Profile
    'profile.yourProfile': 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್',
    'profile.editProfile': 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
    'profile.viewResume': 'ರಿಜ್ಯೂಮೆ ವೀಕ್ಷಿಸಿ',
    'profile.about': 'ಬಗ್ಗೆ',
    'profile.skills': 'ಕೌಶಲ್ಯಗಳು',
    'profile.experience': 'ಅನುಭವ',
    'profile.applications': 'ಅರ್ಜಿಗಳು',
    'profile.saved': 'ಸಂರಕ್ಷಿತ ಕೆಲಸಗಳು',
    
    // Messages
    'messages.title': 'ಸಂದೇಶಗಳು',
    'messages.noMessages': 'ಇನ್ನೂ ಸಂದೇಶಗಳಿಲ್ಲ',
    'messages.typeMessage': 'ಸಂದೇಶವನ್ನು ಟೈಪ್ ಮಾಡಿ...',
    'messages.send': 'ಕಳುಹಿಸಿ',
    'messages.today': 'ಇಂದು',
    'messages.yesterday': 'ನಿನ್ನೆ',
    
    // Notifications
    'notifications.title': 'ಸೂಚನೆಗಳು',
    'notifications.noNotifications': 'ಸೂಚನೆಗಳಿಲ್ಲ',
    'notifications.markAllRead': 'ಎಲ್ಲವನ್ನೂ ಓದಿದ ಎಂದು ಗುರುತಿಸಿ',
    'notifications.clear': 'ಎಲ್ಲವನ್ನೂ ತೆರವುಗೊಳಿಸಿ',
    
    // Settings
    'settings.title': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'settings.editProfile': 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
    'settings.notifications': 'ಸೂಚನೆಗಳು',
    'settings.privacy': 'ಗೌಪ್ಯತೆ',
    'settings.help': 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',
    'settings.language': 'ಭಾಷೆ',
    'settings.darkMode': 'ಡಾರ್ಕ್ ಮೋಡ್',
    'settings.logout': 'ಲಾಗ್ ಔಟ್',
    'settings.jobAlerts': 'ಕೆಲಸ ಎಚ್ಚರಿಕೆಗಳು',
    'settings.messages': 'ಸಂದೇಶಗಳು',
    'settings.promotions': 'ಪ್ರಚಾರಗಳು',
    'settings.reminders': 'ನೆನಪಿನ ವಿಷಯಗಳು',
    'settings.account': 'ಖಾತೆ',
    'settings.preferences': 'ಆದ್ಯತೆಗಳು',
    'settings.about': 'ಬಗ್ಗೆ',
    
    // About Us
    'about.title': 'ನಮ್ಮ ಬಗ್ಗೆ',
    'about.salonJobsIndia': 'ಸ್ಯಾಲೂನ್ ಕೆಲಸಗಳು ಭಾರತ',
    'about.description': 'ಸ್ಯಾಲೂನ್ ವೃತ್ತಿಪರರನ್ನು ಅವಕಾಶಗಳೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಿ',
    'about.mission': 'ನಮ್ಮ ಮಿಷನ್',
    'about.missionText': 'ಸ್ಯಾಲೂನ್ ವೃತ್ತಿಪರರು ಮತ್ತು ವ್ಯವಸಾಯಗಳನ್ನು ತಂತ್ರಜ್ಞಾನದ ಮೂಲಕ ಸಶಕ್ತರು ಮಾಡಿ',
    'about.contactUs': 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
    'about.email': 'ಇಮೇಲ್',
    'about.phone': 'ಫೋನ್',
    'about.website': 'ವೆಬ್‌ಸೈಟ್',
    'about.followUs': 'ನಮ್ಮನ್ನು ಅನುಸರಿಸಿ',
    
    // Create Job
    'job.createJob': 'ಕೆಲಸ ಪೋಸ್ಟಿಂಗ್ ರಚಿಸಿ',
    'job.salonName': 'ಸ್ಯಾಲೂನ್ ಹೆಸರು',
    'job.selectRole': 'ಪಾತ್ರವನ್ನು ಆರಿಸಿ',
    'job.customRole': 'ಕಸ್ಟಮ್ ಪಾತ್ರ',
    'job.salary': 'ಸಂಬಳ',
    'job.description': 'ಕೆಲಸ ವಿವರಣೆ',
    'job.uploadLogo': 'ಸ್ಯಾಲೂನ್ ಲೋಗೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    'job.uploadScreenshot': 'ಪೇಮೆಂಟ್ ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    'job.postJob': 'ಕೆಲಸವನ್ನು ಪೋಸ್ಟ್ ಮಾಡಿ',
    'job.uploadImage': 'ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    'job.fileSize': 'ಫೈಲ್ ಗಾತ್ರ',
    'job.paymentDetails': 'ಪೇಮೆಂಟ್ ವಿವರಗಳು',
    'job.scanQR': 'ಕೆಳಗಿನ QR ಕೋಡ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಅಥವಾ UPI ಗೆ ಪೇಮೆಂಟ್ ಮಾಡಿ:',
    'job.payAmount': 'ನಿಖುಂಜವಾಗಿ ಪೇಮೆಂಟ್ ಮಾಡಿ',
    'job.takeScreenshot': 'ಪೇಮೆಂಟ್ ದೃಢೀಕರಣದ ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ತೆಗೆದುಕೋ',
    'job.uploadScreenshot': 'ಕೆಳಗೆ ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    'job.confirmation': 'ದೃಢೀಕರಣ',
    'job.preview': 'ಪೂರ್ವವೀಕ್ಷಣೆ',
    'job.postingDetails': 'ಕೆಲಸ ಪೋಸ್ಟಿಂಗ್ ವಿವರಗಳು',
    
    // Credit Payment
    'credit.addCredits': 'ಕ್ರೆಡಿಟ್ ಸೇರಿಸಿ',
    'credit.currentCredits': 'ವರ್ತಮಾನ ಕ್ರೆಡಿಟ್',
    'credit.buyCredits': 'ಕ್ರೆಡಿಟ್ ಖರೀದಿಸಿ',
    'credit.selectAmount': 'ಮೊತ್ತವನ್ನು ಆರಿಸಿ',
    'credit.checkout': 'ಚೆಕ್ಔಟ್',
    
    // Owner Panel
    'owner.manageJobs': 'ಕೆಲಸ ಪೋಸ್ಟಿಂಗ್ ನಿರ್ವಹಿಸಿ',
    'owner.activeListings': 'ಸಕ್ರಿಯ ಪಟ್ಟಿ',
    'owner.viewApplications': 'ಅರ್ಜಿಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    'owner.editJob': 'ಕೆಲಸವನ್ನು ಸಂಪಾದಿಸಿ',
    'owner.deleteJob': 'ಕೆಲಸವನ್ನು ಅಳಿಸಿ',
    'owner.unpublish': 'ಪ್ರಕಾಶನವನ್ನು ರದ್ದುಗೊಳಿಸಿ',
    'owner.publish': 'ಪ್ರಕಾಶಿಸಿ',
    'owner.noActiveJobs': 'ಕೆಲಸದ ಸಕ್ರಿಯ ಪೋಸ್ಟಿಂಗ್ ಇಲ್ಲ',
    'owner.createNewJob': 'ಹೊಸ ಕೆಲಸವನ್ನು ರಚಿಸಿ',
    
    // Salon Profile Setup
    'salon.setupProfile': 'ನಿಮ್ಮ ಸ್ಯಾಲೂನ್ ಪ್ರೊಫೈಲ್ ಸೆಟ ಅಪ್ ಮಾಡಿ',
    'salon.salonName': 'ಸ್ಯಾಲೂನ್ ಹೆಸರು',
    'salon.address': 'ವಿಳಾಸ',
    'salon.phone': 'ಫೋನ್',
    'salon.email': 'ಇಮೇಲ್',
    'salon.description': 'ವಿವರಣೆ',
    'salon.uploadLogo': 'ಲೋಗೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    'salon.continue': 'ಮುಂದುವರೆಯಿರಿ',
    
    // General
    'common.save': 'ಸಂರಕ್ಷಿಸಿ',
    'common.cancel': 'ರದ್ದುಗೊಳಿಸಿ',
    'common.delete': 'ಅಳಿಸಿ',
    'common.edit': 'ಸಂಪಾದಿಸಿ',
    'common.loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    'common.error': 'ದೋಷ',
    'common.success': 'ಯಶಸ್ವಿ',
    'common.back': 'ವಹಿಸಿಕೊಳ್ಳಿ',
    'common.next': 'ಮುಂದೆ',
    'common.remember': 'ನೆನಪು ಹೇಳಿ',
    'common.logout': 'ಲಾಗ್ ಔಟ್',
    'common.confirm': 'ದೃಢೀಕರಿಸಿ',
    'common.yes': 'ಹೌದು',
    'common.no': 'ಇಲ್ಲ',
  },

  Gujarati: {
    // Auth
    'auth.title': 'પાછા આવીને સ્વાગત છે',
    'auth.createAccount': 'ખાતું બનાવો',
    'auth.signInSubtitle': 'ચાલુ રાખવા માટે સાઇન ઇન કરો',
    'auth.signUpSubtitle': 'શરુ કરવા માટે સાઇન અપ કરો',
    'auth.signIn': 'સાઇન ઇન કરો',
    'auth.signUp': 'સાઇન અપ કરો',
    'auth.email': 'ઈમેલ',
    'auth.password': 'પાસવર્ડ',
    'auth.phone': 'ફોન નંબર',
    'auth.name': 'સંપૂર્ણ નામ',
    'auth.forgotPassword': 'પાસવર્ડ ભૂલી ગયા?',
    'auth.dontHaveAccount': 'ખાતું નથી?',
    'auth.alreadyHaveAccount': 'પહેલાથી ખાતું છે?',
    
    'role.selectRole': 'તમારી ભૂમિકા પસંદ કરો',
    'role.jobSeeker': 'જોબ શોધનાર',
    'role.salonOwner': 'સલૂન માલિક',
    'role.findJobs': 'નોકરીઓ શોધો',
    'role.manageJobs': 'નોકરીઓ સંચાલિત કરો',
    'role.description1': 'સલૂન નોકરીઓ શોધો અને અરજી કરો',
    'role.description2': 'નોકરીની ખાલીપૂર્વી પોસ્ટ અને સંચાલિત કરો',
    
    'splash.poweredBy': 'Fitonze Private Limited દ્વારા સંચાલિત',
    'nav.home': 'હોમ',
    'nav.messages': 'સંદેશ',
    'nav.notifications': 'સૂચનાઓ',
    'nav.profile': 'પ્રોફાઇલ',
    'nav.settings': 'સેટિંગ્સ',
    'nav.about': 'આપણા વિશે',
    
    'job.searchJobs': 'નોકરીઓ, સલૂન્સ, ભૂમિકાઓ શોધો...',
    'job.filter': 'ફિલ્ટર',
    'job.salary': 'પગાર',
    'job.experience': 'અનુભવ',
    'job.location': 'સ્થાન',
    'job.unlock': 'અનલૉક કરો',
    'job.unlockProfile': 'પ્રોફાઇલ અનલૉક કરો',
    'job.message': 'સંદેશ',
    'job.apply': 'હવે અરજી કરો',
    'job.saved': 'સંગ્રહિત',
    'job.unsave': 'અનસેવ કરો',
    'job.save': 'સંગ્રહ કરો',
    'job.rating': 'રેટિંગ',
    'job.reviews': 'સમીક્ષાઓ',
    'job.distance': 'કિમી દૂર',
    'job.accommodation': 'આવાસ',
    'job.foodProvided': 'ખોરાક આપવામાં આવે છે',
    'job.noJobs': 'કોઈ નોકરી મળી નહીં',
    'job.interested': 'નમસ્તે! મને આ પદમાં રસ છે. મને અનુભવ છે...',
    'job.areaPlaceholder': 'પ્રદેશ અથવા શહેર દાખલ કરો...',
    
    'resume.buildResume': 'તમારું રેઝ્યુમે બનાવો',
    'resume.name': 'સંપૂર્ણ નામ',
    'resume.role': 'પોસ્ટ',
    'resume.experience': 'વર્ષોનો અનુભવ',
    'resume.skills': 'કૌશલ્ય',
    'resume.expectedSalary': 'અપેક્ષિત પગાર',
    'resume.location': 'સ્થાન',
    'resume.continue': 'ચાલુ રાખો',
    'resume.next': 'આગલું',
    'resume.skip': 'છોડી દો',
    
    'subscription.title': 'વધુ ફીચર્સ અનલૉક કરો',
    'subscription.premium': 'પ્રીમિયમ',
    'subscription.features': 'અનમર્યાદિત નોકરીની અરજીઓ',
    'subscription.price': '₹99/મહિનો',
    'subscription.buyNow': 'હવે ખરીદો',
    'subscription.unlimitedApplications': 'અનમર્યાદિત અરજીઓ',
    'subscription.priorityMatching': 'પ્રાધાન્ય નોકરી મેચિંગ',
    'subscription.directContact': 'સલૂન્સ સાથે સીધો સંપર્ક',
    
    'results.applicants': 'અરજીદારો',
    'results.applications': 'અરજીઓ',
    'results.title': 'તમારી અરજીઓ',
    
    'profile.yourProfile': 'તમારી પ્રોફાઇલ',
    'profile.editProfile': 'પ્રોફાઇલ સંપાદિત કરો',
    'profile.viewResume': 'રેઝ્યુમે જુઓ',
    'profile.about': 'વિશે',
    'profile.skills': 'કૌશલ્ય',
    'profile.experience': 'અનુભવ',
    'profile.applications': 'અરજીઓ',
    'profile.saved': 'સંગ્રહિત નોકરીઓ',
    
    'messages.title': 'સંદેશ',
    'messages.noMessages': 'હજી કોઈ સંદેશ નથી',
    'messages.typeMessage': 'સંદેશ ટાઇપ કરો...',
    'messages.send': 'મોકલો',
    'messages.today': 'આજ',
    'messages.yesterday': 'ગતકાલ',
    
    'notifications.title': 'સૂચનાઓ',
    'notifications.noNotifications': 'કોઈ સૂચનાઓ નથી',
    'notifications.markAllRead': 'બધું વાચેલું તરીકે ચિહ્નિત કરો',
    'notifications.clear': 'બધું સાફ કરો',
    
    'settings.title': 'સેટિંગ્સ',
    'settings.editProfile': 'પ્રોફાઇલ સંપાદિત કરો',
    'settings.notifications': 'સૂચનાઓ',
    'settings.privacy': 'ગોપનીયતા',
    'settings.help': 'મદદ અને સહાય',
    'settings.language': 'ભાષા',
    'settings.darkMode': 'ડાર્ક મોડ',
    'settings.logout': 'લૉગ આઉટ',
    'settings.jobAlerts': 'નોકરી ચેતવણીઓ',
    'settings.messages': 'સંદેશ',
    'settings.promotions': 'પ્રમોશનો',
    'settings.reminders': 'રિમાઇન્ડર્સ',
    'settings.account': 'ખાતું',
    'settings.preferences': 'પસંદગીઓ',
    'settings.about': 'વિશે',
    
    'about.title': 'આપણા વિશે',
    'about.salonJobsIndia': 'સલૂન જોબ્સ ઈન્ડિયા',
    'about.description': 'સલૂન વ્યાવસાયિકોને તકો સાથે જોડો',
    'about.mission': 'આપણું મિશન',
    'about.missionText': 'સલૂન વ્યાવસાયિકો અને વ્યવસાયોને તકનીક દ્વારા સશક્ત બનાવો',
    'about.contactUs': 'અમને સંપર્ક કરો',
    'about.email': 'ઈમેલ',
    'about.phone': 'ફોન',
    'about.website': 'વેબસાઇટ',
    'about.followUs': 'અમને અનુસરો',
    
    'job.createJob': 'નોકરી પોસ્ટિંગ બનાવો',
    'job.salonName': 'સલૂન નામ',
    'job.selectRole': 'ભૂમિકા પસંદ કરો',
    'job.customRole': 'કસ્ટમ રોલ',
    'job.salary': 'પગાર',
    'job.description': 'નોકરીનું વર્ણન',
    'job.uploadLogo': 'સલૂન લોગો અપલોડ કરો',
    'job.uploadScreenshot': 'પેમેન્ટ સ્ક્રીનશોટ અપલોડ કરો',
    'job.postJob': 'નોકરી પોસ્ટ કરો',
    'job.uploadImage': 'ઈમેજ અપલોડ કરો',
    'job.fileSize': 'ફાઇલ સાઈজ',
    'job.paymentDetails': 'ચુક્તી વિગત',
    'job.scanQR': 'નીચે QR કોડ સ્કેન કરો અથવા UPI ને ચુક્તી કરો:',
    'job.payAmount': 'બરાબર ચુક્તી કરો',
    'job.takeScreenshot': 'ચુક્તી સુનિશ્ચિતીકરણનો સ્ક્રીનશોટ લો',
    'job.uploadScreenshot': 'નીચે સ્ક્રીનશોટ અપલોડ કરો',
    'job.confirmation': 'સુનિશ્ચિતીકરણ',
    'job.preview': 'પૂર્વદર્શન',
    'job.postingDetails': 'નોકરી પોસ્ટિંગ વિગત',
    
    'credit.addCredits': 'ક્રેડિટ ઉમેરો',
    'credit.currentCredits': 'વર્તમાન ક્રેડિટ',
    'credit.buyCredits': 'ક્રેડિટ ખરીદો',
    'credit.selectAmount': 'રકમ પસંદ કરો',
    'credit.checkout': 'ચેકઆઉટ',
    
    'owner.manageJobs': 'નોકરી પોસ્ટિંગ સંચાલિત કરો',
    'owner.activeListings': 'સક્રિય સૂચીઓ',
    'owner.viewApplications': 'અરજીઓ જુઓ',
    'owner.editJob': 'નોકરી સંપાદિત કરો',
    'owner.deleteJob': 'નોકરી કાઢી મૂકો',
    'owner.unpublish': 'અપ્રકાશિત કરો',
    'owner.publish': 'પ્રકાશિત કરો',
    'owner.noActiveJobs': 'કોઈ સક્રિય નોકરી પોસ્ટિંગ નથી',
    'owner.createNewJob': 'નવી નોકરી બનાવો',
    
    'salon.setupProfile': 'તમારી સલૂન પ્રોફાઇલ સેટ કરો',
    'salon.salonName': 'સલૂન નામ',
    'salon.address': 'સરનામું',
    'salon.phone': 'ફોન',
    'salon.email': 'ઈમેલ',
    'salon.description': 'વર્ણન',
    'salon.uploadLogo': 'લોગો અપલોડ કરો',
    'salon.continue': 'ચાલુ રાખો',
    
    'common.save': 'સંગ્રહ કરો',
    'common.cancel': 'રદ કરો',
    'common.delete': 'કાઢી મૂકો',
    'common.edit': 'સંપાદિત કરો',
    'common.loading': 'લોડ થઇ રહ્યું છે...',
    'common.error': 'ભૂલ',
    'common.success': 'સફલતા',
    'common.back': 'પાછું',
    'common.next': 'આગલું',
    'common.remember': 'યાદ રાખો',
    'common.logout': 'લૉગ આઉટ',
    'common.confirm': 'સુનિશ્ચિત કરો',
    'common.yes': 'હા',
    'common.no': 'ના',
  },

  Malayalam: {
    // Auth
    'auth.title': 'സ്വാഗതം തിരിച്ചെത്തിയതിന്',
    'auth.createAccount': 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    'auth.signInSubtitle': 'തുടരുന്നതിന് സൈൻ ഇൻ ചെയ്യുക',
    'auth.signUpSubtitle': 'തുടങ്ങാൻ സൈൻ അപ്പ് ചെയ്യുക',
    'auth.signIn': 'സൈൻ ഇൻ ചെയ്യുക',
    'auth.signUp': 'സൈൻ അപ്പ് ചെയ്യുക',
    'auth.email': 'ഇമെയിൽ',
    'auth.password': 'പാസ്‌വേഡ്',
    'auth.phone': 'ഫോൻ നമ്പർ',
    'auth.name': 'പൂർണ്ണ നാമം',
    'auth.forgotPassword': 'പാസ്‌വേഡ് മറന്നുവോ?',
    'auth.dontHaveAccount': 'അക്കൗണ്ട് ഇല്ലയോ?',
    'auth.alreadyHaveAccount': 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?',
    
    'role.selectRole': 'നിങ്ങളുടെ പാത്ര തിരഞ്ഞെടുക്കുക',
    'role.jobSeeker': 'ജോലി തെരയുന്നയാൾ',
    'role.salonOwner': 'സലുൻ ഉടമ',
    'role.findJobs': 'ജോലികൾ കണ്ടെത്തുക',
    'role.manageJobs': 'ജോലികൾ കൈകാര്യം ചെയ്യുക',
    'role.description1': 'സലുൻ ജോലികൾ അന്വേഷിച്ച് അപേക്ഷിക്കുക',
    'role.description2': 'ജോലിയുടെ തുറക്കലുകൾ പോസ്റ്റ് ചെയ്യുക ഡ് കൈകാര്യം ചെയ്യുക',
    
    'splash.poweredBy': 'Fitonze Private Limited നിർവ്വഹിച്ചത്',
    'nav.home': 'ഹോം',
    'nav.messages': 'സന്ദേശങ്ങൾ',
    'nav.notifications': 'അറിയിപ്പുകൾ',
    'nav.profile': 'പ്രൊഫൈൽ',
    'nav.settings': 'ക്രമീകരണങ്ങൾ',
    'nav.about': 'ഞങ്ങളെ കുറിച്ച്',
    
    'job.searchJobs': 'ജോലികൾ, സലുൻ, പാത്രങ്ങൾ അന്വേഷിക്കുക...',
    'job.filter': 'ഫിൽട്ടർ',
    'job.salary': 'വേതനം',
    'job.experience': 'അനുഭവം',
    'job.location': 'സ്ഥാനം',
    'job.unlock': 'അൻലോക്ക് ചെയ്യുക',
    'job.unlockProfile': 'പ്രൊഫൈൽ അൻലോക്ക് ചെയ്യുക',
    'job.message': 'സന്ദേശം',
    'job.apply': 'ഇപ്പോൾ അപേക്ഷിക്കുക',
    'job.saved': 'സംരക്ഷിത',
    'job.unsave': 'സംരക്ഷണം നീക്കം കളിക്കുക',
    'job.save': 'സംരക്ഷിക്കുക',
    'job.rating': 'റേറ്റിംഗ്',
    'job.reviews': 'റിവ്യൂകൾ',
    'job.distance': 'കിലോമീറ്റർ അകലെ',
    'job.accommodation': 'താമസം',
    'job.foodProvided': 'ഭക്ഷണം നൽകിയിരിക്കുന്നു',
    'job.noJobs': 'ജോലികൾ കണ്ടെത്തിയില്ല',
    'job.interested': 'നമസ്കാരം! ഈ പദത്തിൽ എനിക്ക് താൽപ്പര്യമുണ്ട്. എനിക്ക് അനുഭവമുണ്ട്...',
    'job.areaPlaceholder': 'പ്രദേശം അല്ലെങ്കിൽ നഗരം നൽകുക...',
    
    'resume.buildResume': 'നിങ്ങളുടെ റെസ്യൂമെ നിർമ്മിക്കുക',
    'resume.name': 'പൂർണ്ണ നാമം',
    'resume.role': 'സ്ഥാനം',
    'resume.experience': 'വർഷങ്ങളുടെ അനുഭവം',
    'resume.skills': 'കഴിവുകൾ',
    'resume.expectedSalary': 'പ്രതീക്ഷിക്കുന്ന വേതനം',
    'resume.location': 'സ്ഥാനം',
    'resume.continue': 'തുടരുക',
    'resume.next': 'അടുത്തത്',
    'resume.skip': 'ഉയർത്തിവിടുക',
    
    'subscription.title': 'കൂടുതൽ ഫീച്ചറുകൾ അൻലോക്ക് ചെയ്യുക',
    'subscription.premium': 'പ്രിമിയം',
    'subscription.features': 'സീമാനിർധിത ജോലി അപേക്ഷകൾ',
    'subscription.price': '₹99/മാസം',
    'subscription.buyNow': 'ഇപ്പോൾ വാങ്ങുക',
    'subscription.unlimitedApplications': 'സീമാനിർധിത അപേക്ഷകൾ',
    'subscription.priorityMatching': 'പ്രാധാന്യത ജോലി പൊരുത്തം',
    'subscription.directContact': 'സലുനുകളുമായി നേരിട്ടുള്ള സമ്പർക്കം',
    
    'results.applicants': 'അപേക്ഷകർ',
    'results.applications': 'അപേക്ഷകൾ',
    'results.title': 'നിങ്ങളുടെ അപേക്ഷകൾ',
    
    'profile.yourProfile': 'നിങ്ങളുടെ പ്രൊഫൈൽ',
    'profile.editProfile': 'പ്രൊഫൈൽ തിരുത്തുക',
    'profile.viewResume': 'റെസ്യൂമെ കാണുക',
    'profile.about': 'കുറിച്ച്',
    'profile.skills': 'കഴിവുകൾ',
    'profile.experience': 'അനുഭവം',
    'profile.applications': 'അപേക്ഷകൾ',
    'profile.saved': 'സംരക്ഷിത ജോലികൾ',
    
    'messages.title': 'സന്ദേശങ്ങൾ',
    'messages.noMessages': 'ഇതുവരെ സന്ദേശങ്ങളൊന്നുമില്ല',
    'messages.typeMessage': 'ഒരു സന്ദേശം ടൈപ്പ് ചെയ്യുക...',
    'messages.send': 'അയയ്ക്കുക',
    'messages.today': 'ഇന്ന്',
    'messages.yesterday': 'നാളെ',
    
    'notifications.title': 'അറിയിപ്പുകൾ',
    'notifications.noNotifications': 'അറിയിപ്പുകളൊന്നുമില്ല',
    'notifications.markAllRead': 'എല്ലാം വായിച്ചതായി അടയാളപ്പെടുത്തുക',
    'notifications.clear': 'എല്ലാം മായ്ക്കുക',
    
    'settings.title': 'ക്രമീകരണങ്ങൾ',
    'settings.editProfile': 'പ്രൊഫൈൽ തിരുത്തുക',
    'settings.notifications': 'അറിയിപ്പുകൾ',
    'settings.privacy': 'സ്വകാര്യത',
    'settings.help': 'സഹായത്ത് ഓ സപ്പോർട്ട്',
    'settings.language': 'ഭാഷ',
    'settings.darkMode': 'ഡാർക് മോഡ്',
    'settings.logout': 'ലോഗ് ഔട്ട്',
    'settings.jobAlerts': 'ജോലി മുന്നറിപ്പുകൾ',
    'settings.messages': 'സന്ദേശങ്ങൾ',
    'settings.promotions': 'പ്രമോഷനുകൾ',
    'settings.reminders': 'സ്മരണീയങ്ങൾ',
    'settings.account': 'അക്കൗണ്ട്',
    'settings.preferences': 'ക്രമീകരണങ്ങൾ',
    'settings.about': 'കുറിച്ച്',
    
    'about.title': 'ഞങ്ങളെ കുറിച്ച്',
    'about.salonJobsIndia': 'സലുൻ ജോലികൾ ഇന്ത്യ',
    'about.description': 'സലുൻ പ്രൊഫേഷനലുകളെ അവസരങ്ങളുമായി ബന്ധിപ്പിക്കുക',
    'about.mission': 'ഞങ്ങളുടെ ലക്ഷ്യം',
    'about.missionText': 'സലുൻ പ്രൊഫേഷനലുകളെയും ബിസിനസുകളെയും സാങ്കേതികതയിലൂടെ ശക്തിപ്പെടുത്തുക',
    'about.contactUs': 'ഞങ്ങളെ സമ്പർക്കം ചെയ്യുക',
    'about.email': 'ഇമെയിൽ',
    'about.phone': 'ഫോൻ',
    'about.website': 'വെബ്സൈറ്റ്',
    'about.followUs': 'ഞങ്ങളെ പിന്തുടരുക',
    
    'job.createJob': 'ജോലി പോസ്റ്റിംഗ് സൃഷ്ടിക്കുക',
    'job.salonName': 'സലുൻ പേര്',
    'job.selectRole': 'പാത്ര തിരഞ്ഞെടുക്കുക',
    'job.customRole': 'കസ്റ്റം റോൾ',
    'job.salary': 'വേതനം',
    'job.description': 'ജോലിയുടെ വിവരണം',
    'job.uploadLogo': 'സലുൻ ലോഗോ അപ്‌ലോഡ് ചെയ്യുക',
    'job.uploadScreenshot': 'പേമെന്റ് സ്ക്രീൻശോട്ട് അപ്‌ലോഡ് ചെയ്യുക',
    'job.postJob': 'ജോലി പോസ്റ്റ് ചെയ്യുക',
    'job.uploadImage': 'ഇമേജ് അപ്‌ലോഡ് ചെയ്യുക',
    'job.fileSize': 'ഫയൽ വലുപ്പം',
    'job.paymentDetails': 'പേമെന്റ് വിവരങ്ങൾ',
    'job.scanQR': 'താഴെ കാണുന്ന QR കോഡ് സ്കാൻ ചെയ്യുക അല്ലെങ്കിൽ UPI ൽ പേമെന്റ് ചെയ്യുക:',
    'job.payAmount': 'കൃത്യമായി പേമെന്റ് ചെയ്യുക',
    'job.takeScreenshot': 'പേമെന്റ് സ്ഥിരീകരണത്തിന്റെ സ്ക്രീൻശോട്ട് എടുക്കുക',
    'job.uploadScreenshot': 'താഴെ സ്ക്രീൻശോട്ട് അപ്‌ലോഡ് ചെയ്യുക',
    'job.confirmation': 'സ്ഥിരീകരണം',
    'job.preview': 'പ്രിവ്യൂ',
    'job.postingDetails': 'ജോലി പോസ്റ്റിംഗ് വിവരങ്ങൾ',
    
    'credit.addCredits': 'ക്രെഡിറ്റ് ചേർക്കുക',
    'credit.currentCredits': 'നിലവിലെ ക്രെഡിറ്റ്',
    'credit.buyCredits': 'ക്രെഡിറ്റ് വാങ്ങുക',
    'credit.selectAmount': 'തുക തിരഞ്ഞെടുക്കുക',
    'credit.checkout': 'ചെക്ക്আউട്ട്',
    
    'owner.manageJobs': 'ജോലി പോസ്റ്റിംഗ് കൈകാര്യം ചെയ്യുക',
    'owner.activeListings': 'സജീവ ലിസ്റ്റിംഗുകൾ',
    'owner.viewApplications': 'അപേക്ഷകൾ കാണുക',
    'owner.editJob': 'ജോലി തിരുത്തുക',
    'owner.deleteJob': 'ജോലി മായ്ക്കുക',
    'owner.unpublish': 'പ്രസിദ്ധീകരണം നിരസിക്കുക',
    'owner.publish': 'പ്രസിദ്ധീകരിക്കുക',
    'owner.noActiveJobs': 'സജീവ ജോലി പോസ്റ്റിംഗ് ഇല്ല',
    'owner.createNewJob': 'പുതിയ ജോലി സൃഷ്ടിക്കുക',
    
    'salon.setupProfile': 'നിങ്ങളുടെ സലുൻ പ്രൊഫൈൽ സെറ്റപ്പ് ചെയ്യുക',
    'salon.salonName': 'സലുൻ പേര്',
    'salon.address': 'സ്ഥാനം',
    'salon.phone': 'ഫോൻ',
    'salon.email': 'ഇമെയിൽ',
    'salon.description': 'വിവരണം',
    'salon.uploadLogo': 'ലോഗോ അപ്‌ലോഡ് ചെയ്യുക',
    'salon.continue': 'തുടരുക',
    
    'common.save': 'സംരക്ഷിക്കുക',
    'common.cancel': 'റദ്ദാക്കുക',
    'common.delete': 'മായ്ക്കുക',
    'common.edit': 'തിരുത്തുക',
    'common.loading': 'ലോഡ് ചെയ്യുന്നു...',
    'common.error': 'പിശക്',
    'common.success': 'സഫലം',
    'common.back': 'പിന്നിലേക്ക്',
    'common.next': 'അടുത്തത്',
    'common.remember': 'ഓർക്കുക',
    'common.logout': 'ലോഗ് ഔട്ട്',
    'common.confirm': 'സ്ഥിരീകരിക്കുക',
    'common.yes': 'അതെ',
    'common.no': 'ഇല്ല',
  },

  Marathi: {
    // Auth
    'auth.title': 'पुन्हा स्वागत आहे',
    'auth.createAccount': 'खाते तयार करा',
    'auth.signInSubtitle': 'सुरू ठेवण्यासाठी साइन इन करा',
    'auth.signUpSubtitle': 'सुरुवात करण्यासाठी साइन अप करा',
    'auth.signIn': 'साइन इन करा',
    'auth.signUp': 'साइन अप करा',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'auth.phone': 'फोन नंबर',
    'auth.name': 'पूर्ण नाव',
    'auth.forgotPassword': 'पासवर्ड विसरलात?',
    'auth.dontHaveAccount': 'खाते नाही का?',
    'auth.alreadyHaveAccount': 'आधीच खाते आहे का?',
    
    'role.selectRole': 'आपली भूमिका निवडा',
    'role.jobSeeker': 'नोकरी शोधणारा',
    'role.salonOwner': 'सलून मालिक',
    'role.findJobs': 'नोकरी शोधा',
    'role.manageJobs': 'नोकरी व्यवस्थापित करा',
    'role.description1': 'सलून नोकरी शोधा आणि अर्ज करा',
    'role.description2': 'नोकरीची रिक्ती पोस्ट करा आणि व्यवस्थापित करा',
    
    'splash.poweredBy': 'Fitonze प्राइवेट लिमिटेड द्वारे चालित',
    'nav.home': 'मुख्यपृष्ठ',
    'nav.messages': 'संदेश',
    'nav.notifications': 'सूचना',
    'nav.profile': 'प्रोफाइल',
    'nav.settings': 'सेटिंग्स',
    'nav.about': 'आমच्या बद्दल',
    
    'job.searchJobs': 'नोकरी, सलून, भूमिका शोधा...',
    'job.filter': 'फिल्टर',
    'job.salary': 'वेतन',
    'job.experience': 'अनुभव',
    'job.location': 'स्थान',
    'job.unlock': 'अनलॉक करा',
    'job.unlockProfile': 'प्रोफाइल अनलॉक करा',
    'job.message': 'संदेश',
    'job.apply': 'आता अर्ज करा',
    'job.saved': 'सेव केले',
    'job.unsave': 'सेव हटवा',
    'job.save': 'सेव करा',
    'job.rating': 'रेटिंग',
    'job.reviews': 'पुनरावलोकन',
    'job.distance': 'किमी दूर',
    'job.accommodation': 'राहणे',
    'job.foodProvided': 'अन्न प्रदान केले जाते',
    'job.noJobs': 'नोकरी आढळली नाही',
    'job.interested': 'नमस्कार! मला या पदात स्वारस्य आहे. मला अनुभव आहे...',
    'job.areaPlaceholder': 'क्षेत्र किंवा शहर प्रविष्ट करा...',
    
    'resume.buildResume': 'आपले रेझ्यूमे बनवा',
    'resume.name': 'पूर्ण नाव',
    'resume.role': 'पद',
    'resume.experience': 'वर्षांचा अनुभव',
    'resume.skills': 'कौशल्य',
    'resume.expectedSalary': 'अपेक्षित वेतन',
    'resume.location': 'स्थान',
    'resume.continue': 'सुरू ठेवा',
    'resume.next': 'पुढील',
    'resume.skip': 'सोडा',
    
    'subscription.title': 'अधिक वैशिष्ट्य अनलॉक करा',
    'subscription.premium': 'प्रीमियम',
    'subscription.features': 'असीमित नोकरी अर्ज',
    'subscription.price': '₹99/महिना',
    'subscription.buyNow': 'आता खरेदी करा',
    'subscription.unlimitedApplications': 'असीमित अर्ज',
    'subscription.priorityMatching': 'प्राधान्यता नोकरी जुळणे',
    'subscription.directContact': 'सलून सह थेट संपर्क',
    
    'results.applicants': 'अर्जदार',
    'results.applications': 'अर्ज',
    'results.title': 'आपले अर्ज',
    
    'profile.yourProfile': 'आपली प्रोफाइल',
    'profile.editProfile': 'प्रोफाइल संपादित करा',
    'profile.viewResume': 'रेझ्यूमे पाहा',
    'profile.about': 'बद्दल',
    'profile.skills': 'कौशल्य',
    'profile.experience': 'अनुभव',
    'profile.applications': 'अर्ज',
    'profile.saved': 'सेव केलेल्या नोकरी',
    
    'messages.title': 'संदेश',
    'messages.noMessages': 'अजून संदेश नाहीत',
    'messages.typeMessage': 'संदेश टाइप करा...',
    'messages.send': 'पाठवा',
    'messages.today': 'आज',
    'messages.yesterday': 'काल',
    
    'notifications.title': 'सूचना',
    'notifications.noNotifications': 'सूचना नाहीत',
    'notifications.markAllRead': 'सर्व पठीत म्हणून चिन्हांकित करा',
    'notifications.clear': 'सर्व साफ करा',
    
    'settings.title': 'सेटिंग्स',
    'settings.editProfile': 'प्रोफाइल संपादित करा',
    'settings.notifications': 'सूचना',
    'settings.privacy': 'गोपनीयता',
    'settings.help': 'मदत आणि समर्थन',
    'settings.language': 'भाषा',
    'settings.darkMode': 'गडद मोड',
    'settings.logout': 'लॉग आउट',
    'settings.jobAlerts': 'नोकरी सतर्कता',
    'settings.messages': 'संदेश',
    'settings.promotions': 'प्रचार',
    'settings.reminders': 'अनुस्मारक',
    'settings.account': 'खाते',
    'settings.preferences': 'प्राधान्यता',
    'settings.about': 'बद्दल',
    
    'about.title': 'आमच्या बद्दल',
    'about.salonJobsIndia': 'सलून जॉब्स इंडिया',
    'about.description': 'सलून व्यावसायिकांना संधीसह जोडा',
    'about.mission': 'आमचे मिशन',
    'about.missionText': 'सलून व्यावसायिक आणि व्यवसायांना तंत्रज्ञानाद्वारे सक्षम करा',
    'about.contactUs': 'आमच्याशी संपर्क करा',
    'about.email': 'ईमेल',
    'about.phone': 'फोन',
    'about.website': 'वेबसाइट',
    'about.followUs': 'आमचे अनुसरण करा',
    
    'job.createJob': 'नोकरी पोस्टिंग तयार करा',
    'job.salonName': 'सलून नाव',
    'job.selectRole': 'भूमिका निवडा',
    'job.customRole': 'कस्टम भूमिका',
    'job.salary': 'वेतन',
    'job.description': 'नोकरीचे वर्णन',
    'job.uploadLogo': 'सलून लोगो अपलोड करा',
    'job.uploadScreenshot': 'पेमेंट स्क्रीनशॉट अपलोड करा',
    'job.postJob': 'नोकरी पोस्ट करा',
    'job.uploadImage': 'प्रतिमा अपलोड करा',
    'job.fileSize': 'फाइल आकार',
    'job.paymentDetails': 'पेमेंट तपशील',
    'job.scanQR': 'खालील QR कोड स्कॅन करा किंवा UPI ला भुगतान करा:',
    'job.payAmount': 'अगदी भुगतान करा',
    'job.takeScreenshot': 'पेमेंट सुनिश्चिताचा स्क्रीनशॉट घ्या',
    'job.uploadScreenshot': 'खालील स्क्रीनशॉट अपलोड करा',
    'job.confirmation': 'सुनिश्चिता',
    'job.preview': 'पूर्वावलोकन',
    'job.postingDetails': 'नोकरी पोस्टिंग तपशील',
    
    'credit.addCredits': 'क्रेडिट जोडा',
    'credit.currentCredits': 'वर्तमान क्रेडिट',
    'credit.buyCredits': 'क्रेडिट खरेदी करा',
    'credit.selectAmount': 'रक्कम निवडा',
    'credit.checkout': 'चेकआउट',
    
    'owner.manageJobs': 'नोकरी पोस्टिंग व्यवस्थापित करा',
    'owner.activeListings': 'सक्रिय सूची',
    'owner.viewApplications': 'अर्ज पाहा',
    'owner.editJob': 'नोकरी संपादित करा',
    'owner.deleteJob': 'नोकरी हटवा',
    'owner.unpublish': 'प्रकाशन रद्द करा',
    'owner.publish': 'प्रकाशित करा',
    'owner.noActiveJobs': 'सक्रिय नोकरी पोस्टिंग नाही',
    'owner.createNewJob': 'नवीन नोकरी तयार करा',
    
    'salon.setupProfile': 'आपली सलून प्रोफाइल सेट अप करा',
    'salon.salonName': 'सलून नाव',
    'salon.address': 'पत्ता',
    'salon.phone': 'फोन',
    'salon.email': 'ईमेल',
    'salon.description': 'वर्णन',
    'salon.uploadLogo': 'लोगो अपलोड करा',
    'salon.continue': 'सुरू ठेवा',
    
    'common.save': 'सेव करा',
    'common.cancel': 'रद्द करा',
    'common.delete': 'हटवा',
    'common.edit': 'संपादित करा',
    'common.loading': 'लोड होत आहे...',
    'common.error': 'त्रुटी',
    'common.success': 'यश',
    'common.back': 'परत',
    'common.next': 'पुढील',
    'common.remember': 'लक्षात ठेवा',
    'common.logout': 'लॉग आउट',
    'common.confirm': 'पुष्टी करा',
    'common.yes': 'होय',
    'common.no': 'नाही',
  },

  Urdu: {
    // Auth
    'auth.title': 'خوش آمدید',
    'auth.createAccount': 'اکاؤنٹ بنائیں',
    'auth.signInSubtitle': 'جاری رکھنے کے لیے سائن ان کریں',
    'auth.signUpSubtitle': 'شروع کرنے کے لیے سائن اپ کریں',
    'auth.signIn': 'سائن ان کریں',
    'auth.signUp': 'سائن اپ کریں',
    'auth.email': 'ای میل',
    'auth.password': 'پاس ورڈ',
    'auth.phone': 'فون نمبر',
    'auth.name': 'مکمل نام',
    'auth.forgotPassword': 'پاس ورڈ بھول گئے؟',
    'auth.dontHaveAccount': 'اکاؤنٹ نہیں ہے؟',
    'auth.alreadyHaveAccount': 'پہلے سے اکاؤنٹ ہے؟',
    
    'role.selectRole': 'اپنا کردار منتخب کریں',
    'role.jobSeeker': 'ملازمت تلاش کار',
    'role.salonOwner': 'سلون مالک',
    'role.findJobs': 'نوکریاں تلاش کریں',
    'role.manageJobs': 'نوکریوں کو منظم کریں',
    'role.description1': 'سلون کی نوکریاں تلاش کریں اور درخواست کریں',
    'role.description2': 'نوکری کی کھلیپن شائع کریں اور منظم کریں',
    
    'splash.poweredBy': 'Fitonze Private Limited کے ذریعے چلایا گیا',
    'nav.home': 'ہوم',
    'nav.messages': 'پیغامات',
    'nav.notifications': 'اطلاعات',
    'nav.profile': 'پروفائل',
    'nav.settings': 'ترتیبات',
    'nav.about': 'ہمارے بارے میں',
    
    'job.searchJobs': 'نوکریاں، سلون، کردار تلاش کریں...',
    'job.filter': 'فلٹر',
    'job.salary': 'تنخواہ',
    'job.experience': 'تجربہ',
    'job.location': 'مقام',
    'job.unlock': 'انلاک کریں',
    'job.unlockProfile': 'پروفائل انلاک کریں',
    'job.message': 'پیغام',
    'job.apply': 'ابھی درخواست کریں',
    'job.saved': 'محفوظ شدہ',
    'job.unsave': 'محفوظ کنسل کریں',
    'job.save': 'محفوظ کریں',
    'job.rating': 'درجہ بندی',
    'job.reviews': 'جائزے',
    'job.distance': 'کلومیٹر دور',
    'job.accommodation': 'رہائش',
    'job.foodProvided': 'کھانا فراہم کیا جاتا ہے',
    'job.noJobs': 'کوئی نوکری نہیں ملی',
    'job.interested': 'السلام علیکم! مجھے یہ نوکری دلچسپ لگتی ہے۔ مجھے تجربہ ہے...',
    'job.areaPlaceholder': 'علاقہ یا شہر درج کریں...',
    
    'resume.buildResume': 'اپنا ریزیومے بنائیں',
    'resume.name': 'مکمل نام',
    'resume.role': 'عہدہ',
    'resume.experience': 'سالوں کا تجربہ',
    'resume.skills': 'ہنر',
    'resume.expectedSalary': 'متوقع تنخواہ',
    'resume.location': 'مقام',
    'resume.continue': 'جاری رکھیں',
    'resume.next': 'اگلا',
    'resume.skip': 'چھوڑ دیں',
    
    'subscription.title': 'مزید خصوصیات انلاک کریں',
    'subscription.premium': 'پریمیم',
    'subscription.features': 'لامحدود نوکری درخواستیں',
    'subscription.price': '₹99/ماہ',
    'subscription.buyNow': 'ابھی خریدیں',
    'subscription.unlimitedApplications': 'لامحدود درخواستیں',
    'subscription.priorityMatching': 'ترجیح نوکری میچنگ',
    'subscription.directContact': 'سلون کے ساتھ براہ راست رابطہ',
    
    'results.applicants': 'متقاضیین',
    'results.applications': 'درخواستیں',
    'results.title': 'آپ کی درخواستیں',
    
    'profile.yourProfile': 'آپ کی پروفائل',
    'profile.editProfile': 'پروفائل میں ترمیم کریں',
    'profile.viewResume': 'ریزیومے دیکھیں',
    'profile.about': 'کے بارے میں',
    'profile.skills': 'ہنر',
    'profile.experience': 'تجربہ',
    'profile.applications': 'درخواستیں',
    'profile.saved': 'محفوظ نوکریاں',
    
    'messages.title': 'پیغامات',
    'messages.noMessages': 'ابھی کوئی پیغام نہیں',
    'messages.typeMessage': 'پیغام ٹائپ کریں...',
    'messages.send': 'بھیجیں',
    'messages.today': 'آج',
    'messages.yesterday': 'کل',
    
    'notifications.title': 'اطلاعات',
    'notifications.noNotifications': 'کوئی اطلاع نہیں',
    'notifications.markAllRead': 'تمام کو پڑھا ہوا نشان زد کریں',
    'notifications.clear': 'سب صاف کریں',
    
    'settings.title': 'ترتیبات',
    'settings.editProfile': 'پروفائل میں ترمیم کریں',
    'settings.notifications': 'اطلاعات',
    'settings.privacy': 'رازداری',
    'settings.help': 'مدد اور سپورٹ',
    'settings.language': 'زبان',
    'settings.darkMode': 'گہرا موڈ',
    'settings.logout': 'لاگ آؤٹ',
    'settings.jobAlerts': 'نوکری کی انتباہات',
    'settings.messages': 'پیغامات',
    'settings.promotions': 'فروغ',
    'settings.reminders': 'یادداشتیں',
    'settings.account': 'اکاؤنٹ',
    'settings.preferences': 'ترجیحات',
    'settings.about': 'کے بارے میں',
    
    'about.title': 'ہمارے بارے میں',
    'about.salonJobsIndia': 'سلون جابس انڈیا',
    'about.description': 'سلون کے پروفیشنلز کو مواقع کے ساتھ جوڑیں',
    'about.mission': 'ہمارا مشن',
    'about.missionText': 'سلون کے پروفیشنلز اور کاروبار کو ٹیکنالوجی کے ذریعے طاقتور بنائیں',
    'about.contactUs': 'ہمسے رابطہ کریں',
    'about.email': 'ای میل',
    'about.phone': 'فون',
    'about.website': 'ویب سائٹ',
    'about.followUs': 'ہمیں فالو کریں',
    
    'job.createJob': 'نوکری کی تشہیر بنائیں',
    'job.salonName': 'سلون کا نام',
    'job.selectRole': 'کردار منتخب کریں',
    'job.customRole': 'حسب ضرورت کردار',
    'job.salary': 'تنخواہ',
    'job.description': 'نوکری کی تفصیل',
    'job.uploadLogo': 'سلون لوگو اپ لوڈ کریں',
    'job.uploadScreenshot': 'ادائیگی کا اسکرین شاٹ اپ لوڈ کریں',
    'job.postJob': 'نوکری شائع کریں',
    'job.uploadImage': 'تصویر اپ لوڈ کریں',
    'job.fileSize': 'فائل کی سائز',
    'job.paymentDetails': 'ادائیگی کی تفصیلات',
    'job.scanQR': 'نیچے QR کوڈ اسکین کریں یا UPI کو ادائیگی کریں:',
    'job.payAmount': 'بالکل ادائیگی کریں',
    'job.takeScreenshot': 'ادائیگی کی تصدیق کا اسکرین شاٹ لیں',
    'job.uploadScreenshot': 'نیچے اسکرین شاٹ اپ لوڈ کریں',
    'job.confirmation': 'تصدیق',
    'job.preview': 'پیشنمائش',
    'job.postingDetails': 'نوکری کی تشہیر کی تفصیلات',
    
    'credit.addCredits': 'کریڈٹ شامل کریں',
    'credit.currentCredits': 'موجودہ کریڈٹ',
    'credit.buyCredits': 'کریڈٹ خریدیں',
    'credit.selectAmount': 'رقم منتخب کریں',
    'credit.checkout': 'چیک آؤٹ',
    
    'owner.manageJobs': 'نوکری کی تشہیر کا انتظام کریں',
    'owner.activeListings': 'فعال فہرستیں',
    'owner.viewApplications': 'درخواستیں دیکھیں',
    'owner.editJob': 'نوکری میں ترمیم کریں',
    'owner.deleteJob': 'نوکری حذف کریں',
    'owner.unpublish': 'شائع کنسل کریں',
    'owner.publish': 'شائع کریں',
    'owner.noActiveJobs': 'کوئی فعال نوکری کی تشہیر نہیں',
    'owner.createNewJob': 'نئی نوکری بنائیں',
    
    'salon.setupProfile': 'اپنی سلون پروفائل سیٹ اپ کریں',
    'salon.salonName': 'سلون کا نام',
    'salon.address': 'پتہ',
    'salon.phone': 'فون',
    'salon.email': 'ای میل',
    'salon.description': 'تفصیل',
    'salon.uploadLogo': 'لوگو اپ لوڈ کریں',
    'salon.continue': 'جاری رکھیں',
    
    'common.save': 'محفوظ کریں',
    'common.cancel': 'منسوخ کریں',
    'common.delete': 'حذف کریں',
    'common.edit': 'ترمیم کریں',
    'common.loading': 'لوڈ ہو رہا ہے...',
    'common.error': 'خرابی',
    'common.success': 'کامیابی',
    'common.back': 'پیچھے',
    'common.next': 'اگلا',
    'common.remember': 'یاد رکھیں',
    'common.logout': 'لاگ آؤٹ',
    'common.confirm': 'تصدیق کریں',
    'common.yes': 'ہاں',
    'common.no': 'نہیں',
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('English')
  const [isClient, setIsClient] = useState(false)

  useEffect(() => {
    setIsClient(true)
    const saved = localStorage.getItem('language') as Language
    if (saved && Object.keys(translations).includes(saved)) {
      setCurrentLanguage(saved)
    }
  }, [])

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language)
    localStorage.setItem('language', language)
  }

  const t = (key: string): string => {
    return translations[currentLanguage][key] || key
  }

  if (!isClient) return <>{children}</>

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
