'use client'

import { createContext, useContext, useState, type ReactNode, useEffect } from 'react'

export type Language = 'English' | 'Hindi' | 'Telugu' | 'Tamil' | 'Kannada' | 'Gujarati' | 'Malayalam' | 'Marathi' | 'Urdu'

interface LanguageContextType {
  currentLanguage: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<Language, Record<string, string>> = {
  English: {
    // Auth & Common
    'auth.title': 'Welcome Back',
    'auth.createAccount': 'Create Account',
    'auth.signInSubtitle': 'Sign In to continue',
    'auth.signUpSubtitle': 'Sign Up to get started',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.phone': 'Phone Number',
    'auth.name': 'Full Name',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.rememberMe': 'Remember me',
    
    // Role Selection
    'role.selectRole': 'Select Your Role',
    'role.jobSeeker': 'Job Seeker',
    'role.salonOwner': 'Salon Owner',
    'role.findJobs': 'Find Jobs',
    'role.manageJobs': 'Manage Jobs',
    'role.description1': 'Search and apply to salon jobs',
    'role.description2': 'Post and manage job openings',
    'role.back': 'Back',
    'role.next': 'Next',
    
    // Navigation & Common
    'nav.home': 'Home',
    'nav.jobs': 'Jobs',
    'nav.messages': 'Messages',
    'nav.chats': 'Chats',
    'nav.notifications': 'Alerts',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.about': 'About Us',
    'nav.dashboard': 'Dashboard',
    'nav.postJob': 'Post Job',
    'owner.manageJobs': 'Manage Jobs',
    'job.createJob': 'Create Job',
    
    // Common UI
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.remember': 'Remember',
    'common.submit': 'Submit',
    'common.logout': 'Logout',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.apply': 'Apply',
    'common.send': 'Send',
    'common.message': 'Message',
    'common.call': 'Call',
    'common.continue': 'Continue',
    'common.skip': 'Skip',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.change': 'Change',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.all': 'All',
    'common.more': 'More',
    'common.view': 'View',
    'common.details': 'Details',
    
    // Splash Screen
    'splash.poweredBy': 'Powered by Fitonze Private Limited',
    
    // Resume Builder
    'resume.title': 'Build Your Resume',
    'resume.buildResume': 'Build Your Resume',
    'resume.uploadPhoto': 'Upload Photo',
    'resume.changePhoto': 'Change Photo',
    'resume.resume': 'Resume',
    'resume.name': 'Name',
    'resume.email': 'Email',
    'resume.phone': 'Phone',
    'resume.experience': 'Experience',
    'resume.desiredRole': 'Desired Role',
    'resume.bio': 'Bio',
    'resume.finalDetails': 'Final Details',
    'resume.saveResume': 'Save Resume',
    'resume.selectRole': 'Select Role',
    'resume.enterBio': 'Enter your bio',
    'resume.years': 'Years',
    
    // Job Discovery
    'jobs.findJobs': 'Find Jobs',
    'jobs.filterJobs': 'Filter Jobs',
    'jobs.searchJobs': 'Search for jobs...',
    'jobs.allJobs': 'All Jobs',
    'jobs.nearby': 'Nearby',
    'jobs.salaryRange': 'Salary Range',
    'jobs.experience': 'Experience',
    'jobs.expereinceRequired': 'Experience Required',
    'jobs.applyNow': 'Apply Now',
    'jobs.jobDetails': 'Job Details',
    'jobs.companyName': 'Company Name',
    'jobs.location': 'Location',
    'jobs.salary': 'Salary',
    'jobs.jobType': 'Job Type',
    'jobs.fullTime': 'Full Time',
    'jobs.partTime': 'Part Time',
    'jobs.contract': 'Contract',
    'jobs.noJobs': 'No jobs found',
    'jobs.loadingJobs': 'Loading jobs...',
    'jobs.shopDetails': 'Shop Details',
    'jobs.viewMore': 'View More',
    'jobs.viewLess': 'View Less',
    'jobs.contactOwner': 'Contact Owner',
    'jobs.shareContact': 'Share Contact',
    'jobs.contactShared': 'Contact Shared',
    'jobs.contactCredits': 'Contact Credits',
    'jobs.buyCredits': 'Buy Credits',
    'jobs.availableCredits': 'Available Credits',
    'jobs.noCredits': 'Insufficient credits',
    'jobs.needCredits': 'You need credits to view contact information',
    'jobs.subscribe': 'Subscribe',
    'jobs.unlimited': 'Unlimited Access',
    'jobs.applied': 'Applied',
    'jobs.applyUnlimited': 'Apply to unlimited jobs',
    
    // Job Results
    'results.jobResults': 'Job Results',
    'results.yourApplications': 'Your Applications',
    'results.applicantDetails': 'Applicant Details',
    'results.viewProfile': 'View Profile',
    'results.contactApplicant': 'Contact Applicant',
    
    // Subscription
    'subscription.upgradeTitle': 'Upgrade to Premium',
    'subscription.choosePlan': 'Choose your plan',
    'subscription.employerPlans': 'Employer Plans',
    'subscription.basicPlan': 'Basic Plan',
    'subscription.premiumPlan': 'Premium Plan',
    'subscription.getVerified': 'Get Verified Badge',
    'subscription.unlimitedApps': 'Unlimited Applications',
    'subscription.priority': 'Priority Support',
    'subscription.monthly': 'Monthly',
    'subscription.yearly': 'Yearly',
    'subscription.features': 'Features',
    'subscription.selectPlan': 'Select Plan',
    'subscription.subscribe': 'Subscribe',
    
    // Verification
    'verify.getVerifiedBadge': 'Get Verified Badge',
    'verify.paymentProcess': 'Payment Process',
    'verify.step1': '1. Our team verifies your payment screenshot',
    'verify.step2': '2. Verified badge is activated on your profile',
    'verify.step3': '3. Badge appears on all your job posts',
    'verify.step4': '3. You receive a notification once approved',
    'verify.clickUpload': 'Click to upload screenshot',
    'verify.completePayment': 'Complete Payment',
    'verify.amount': 'Amount',
    'verify.upiMethods': 'GPay, PhonePe, Paytm, any UPI',
    'verify.paymentScreenshot': 'Payment Screenshot',
    'verify.uploadScreenshot': 'Upload Screenshot',
    
    // Profile
    'profile.myProfile': 'My Profile',
    'profile.editProfile': 'Edit Profile',
    'profile.accountSettings': 'Account Settings',
    'profile.changePhoto': 'Change Photo',
    'profile.dateOfBirth': 'Date of Birth',
    'profile.location': 'Location',
    'profile.experience': 'Experience',
    'profile.bio': 'Bio',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.emailCannotChanged': 'Email cannot be changed',
    'profile.savedJobs': 'Saved Jobs',
    'profile.favoriteJobs': 'Favorite Jobs',
    'profile.applications': 'Applications',
    'profile.preferences': 'Preferences',
    'profile.verified': 'Verified',
    'profile.getVerified': 'Get Verified',
    'profile.joinDate': 'Join Date',
    'profile.viewResume': 'View Resume',
    'profile.changePassword': 'Change Password',
    'profile.twoFactor': 'Two-Factor Authentication',
    'profile.privacy': 'Privacy',
    'profile.notifications': 'Notifications',
    
    // Messages
    'messages.messages': 'Messages',
    'messages.chats': 'Chats',
    'messages.noMessages': 'No messages',
    'messages.startConversation': 'Start a conversation',
    'messages.typeMessage': 'Type your message...',
    'messages.sendMessage': 'Send Message',
    'messages.recentChats': 'Recent Chats',
    'messages.search': 'Search messages...',
    'messages.online': 'Online',
    'messages.offline': 'Offline',
    'messages.typing': 'typing...',
    'messages.blockedUser': 'Blocked User',
    'messages.blockUser': 'Block User',
    'messages.unblock': 'Unblock',
    'messages.delete': 'Delete Chat',
    'messages.markAsRead': 'Mark as Read',
    'messages.markAsUnread': 'Mark as Unread',
    'messages.clearChat': 'Clear Chat',
    'messages.call': 'Call',
    'messages.video': 'Video Call',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.unread': 'unread',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.noNotifications': 'No notifications',
    'notifications.applicationReceived': 'Application Received',
    'notifications.newJobPosted': 'New Job Posted',
    'notifications.profileViewed': 'Profile Viewed',
    'notifications.messageReceived': 'New Message',
    'notifications.jobAlert': 'Job Alert',
    'notifications.applicationStatus': 'Application Status Updated',
    'notifications.contactShared': 'Contact Shared',
    'notifications.creditsAdded': 'Credits Added',
    'notifications.verificationApproved': 'Verification Approved',
    
    // About Us
    'aboutUs.aboutUs': 'About Us',
    'aboutUs.title': 'Fitonze Private Limited',
    'aboutUs.tagline': 'Connect with Top Talent in the Beauty Industry',
    'aboutUs.vision': 'Our Vision',
    'aboutUs.visionDescription': 'To revolutionize the beauty and wellness industry by connecting talented professionals with leading salons',
    'aboutUs.mission': 'Our Mission',
    'aboutUs.missionDescription': 'Empowering beauty professionals and salon owners to build successful careers and thriving businesses',
    'aboutUs.values': 'Our Values',
    'aboutUs.value1': 'Excellence',
    'aboutUs.value2': 'Integrity',
    'aboutUs.value3': 'Innovation',
    'aboutUs.value4': 'Community',
    'aboutUs.features': 'Why Choose Us',
    'aboutUs.feature1': 'Easy Job Matching',
    'aboutUs.feature2': 'Verified Professionals',
    'aboutUs.feature3': '24/7 Support',
    'aboutUs.feature4': 'Secure Payments',
    'aboutUs.contactUs': 'Contact Us',
    'aboutUs.email': 'Email',
    'aboutUs.phone': 'Phone',
    'aboutUs.address': 'Address',
    'aboutUs.followUs': 'Follow Us',
    'aboutUs.termsOfService': 'Terms of Service',
    'aboutUs.privacyPolicy': 'Privacy Policy',
    'aboutUs.contactSupport': 'Contact Support',
    
    // Create Job
    'job.createJob': 'Create Job',
    'job.postJob': 'Post Job',
    'job.jobTitle': 'Job Title',
    'job.jobDescription': 'Job Description',
    'job.location': 'Location',
    'job.salary': 'Salary',
    'job.salaryRange': 'Salary Range',
    'job.jobType': 'Job Type',
    'job.experience': 'Experience Required',
    'job.requiredSkills': 'Required Skills',
    'job.benefits': 'Benefits',
    'job.postJobButton': 'Post Job',
    'job.editJob': 'Edit Job',
    'job.deleteJob': 'Delete Job',
    'job.jobPosted': 'Job Posted Successfully',
    'job.jobUpdated': 'Job Updated Successfully',
    'job.jobDeleted': 'Job Deleted Successfully',
    'job.preview': 'Preview',
    'job.draft': 'Save as Draft',
    'job.publish': 'Publish',
    
    // Owner Panel
    'owner.dashboard': 'Dashboard',
    'owner.activeJobs': 'Active Jobs',
    'owner.closedJobs': 'Closed Jobs',
    'owner.applicants': 'Applicants',
    'owner.statistics': 'Statistics',
    'owner.viewApplications': 'View Applications',
    'owner.acceptApplication': 'Accept',
    'owner.rejectApplication': 'Reject',
    'owner.applicantInfo': 'Applicant Information',
    'owner.resume': 'Resume',
    'owner.contactInfo': 'Contact Information',
    'owner.sendOffer': 'Send Offer',
    'owner.scheduleInterview': 'Schedule Interview',
    'owner.makePayment': 'Make Payment',
    'owner.buyCredits': 'Buy Credits',
    
    // Settings
    'settings.settings': 'Settings',
    'settings.accountSettings': 'Account Settings',
    'settings.privacySettings': 'Privacy Settings',
    'settings.notificationSettings': 'Notification Settings',
    'settings.preferenceSettings': 'Preference Settings',
    'settings.language': 'Language',
    'settings.darkMode': 'Dark Mode',
    'settings.notifications': 'Notifications',
    'settings.emailNotifications': 'Email Notifications',
    'settings.pushNotifications': 'Push Notifications',
    'settings.smsNotifications': 'SMS Notifications',
    'settings.privacy': 'Privacy',
    'settings.profileVisibility': 'Profile Visibility',
    'settings.showOnlineStatus': 'Show Online Status',
    'settings.blockList': 'Block List',
    'settings.twoFactor': 'Two-Factor Authentication',
    'settings.changePassword': 'Change Password',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.confirmPassword': 'Confirm Password',
    'settings.logout': 'Logout',
    'settings.deleteAccount': 'Delete Account',
    'settings.help': 'Help & Support',
    'settings.faq': 'FAQ',
    'settings.contactSupport': 'Contact Support',
    'settings.about': 'About',
    'settings.version': 'Version',
    
    // Credits
    'credits.30Credits': '30 Credits',
    'credits.availableCredits': 'Available Credits',
    'credits.buyCredits': 'Buy Contact Credits',
    'credits.creditUsed': 'Credit Used',
    'credits.creditsRemaining': 'Credits Remaining',
    'credits.lowCredits': 'Low Credits',
    'credits.outOfCredits': 'Out of Credits',
    
    // Salon Profile
    'salon.completeSalonProfile': 'Complete Your Salon Profile',
    'salon.salonName': 'Salon Name',
    'salon.salonDescription': 'Salon Description',
    'salon.salonAddress': 'Salon Address',
    'salon.salonPhone': 'Salon Phone',
    'salon.salonEmail': 'Salon Email',
    'salon.salonWebsite': 'Salon Website',
    'salon.salonType': 'Salon Type',
    'salon.services': 'Services Offered',
    'salon.operatingHours': 'Operating Hours',
    'salon.uploadLogo': 'Upload Logo',
    'salon.uploadCover': 'Upload Cover Photo',
    'salon.saveSalonProfile': 'Save Salon Profile',
    'salon.profileComplete': 'Profile Complete',
    
    // Messages/Errors
    'message.success': 'Success!',
    'message.error': 'Something went wrong',
    'message.pleaseWait': 'Please wait...',
    'message.loading': 'Loading...',
    'message.noData': 'No data available',
    'message.invalidEmail': 'Invalid email address',
    'message.passwordMismatch': 'Passwords do not match',
    'message.fillAllFields': 'Please fill all fields',
    'message.confirmDelete': 'Are you sure?',
    'message.deleteConfirmed': 'Deleted successfully',
  },
  
  Hindi: {
    'auth.title': 'वापस स्वागत है',
    'auth.createAccount': 'खाता बनाएं',
    'auth.signInSubtitle': 'जारी रखने के लिए साइन इन करें',
    'auth.signUpSubtitle': 'शुरुआत करने के लिए साइन अप करें',
    'auth.signIn': 'साइन इन करें',
    'auth.signUp': 'साइन अप करें',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'auth.phone': 'फोन नंबर',
    'auth.name': 'पूरा नाम',
    'auth.forgotPassword': 'पासवर्ड भूल गए?',
    'auth.dontHaveAccount': 'खाता नहीं है?',
    'auth.alreadyHaveAccount': 'पहले से ही खाता है?',
    'auth.rememberMe': 'मुझे याद रखें',
    
    'role.selectRole': 'अपनी भूमिका चुनें',
    'role.jobSeeker': 'नौकरी खोजने वाला',
    'role.salonOwner': 'सैलून मालिक',
    'role.findJobs': 'नौकरियां खोजें',
    'role.manageJobs': 'नौकरियां प्रबंधित करें',
    'role.description1': 'सैलून नौकरियों के लिए खोजें और आवेदन करें',
    'role.description2': 'नौकरी के उद्घाटन पोस्ट करें और प्रबंधित करें',
    'role.back': 'वापस',
    'role.next': 'अगला',
    
    'nav.home': 'घर',
    'nav.jobs': 'नौकरियां',
    'nav.messages': 'संदेश',
    'nav.chats': 'बातचीत',
    'nav.notifications': 'सूचनाएं',
    'nav.profile': 'प्रोफाइल',
    'nav.settings': 'सेटिंग्स',
    'nav.about': 'हमारे बारे में',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.postJob': 'नौकरी पोस्ट करें',
    'owner.manageJobs': 'नौकरियां प्रबंधित करें',
    'job.createJob': 'नौकरी बनाएं',
    
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.delete': 'हटाएं',
    'common.edit': 'संपादित करें',
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.success': 'सफलता',
    'common.back': 'वापस',
    'common.next': 'अगला',
    'common.remember': 'याद रखें',
    'common.submit': 'जमा करें',
    'common.logout': 'लॉगआउट',
    'common.close': 'बंद करें',
    'common.search': 'खोजें',
    'common.filter': 'फ़िल्टर',
    'common.apply': 'आवेदन करें',
    'common.send': 'भेजें',
    'common.message': 'संदेश',
    'common.call': 'कॉल करें',
    'common.continue': 'जारी रखें',
    'common.skip': 'छोड़ें',
    'common.download': 'डाउनलोड करें',
    'common.upload': 'अपलोड करें',
    'common.change': 'बदलें',
    'common.confirm': 'पुष्टि करें',
    'common.yes': 'हां',
    'common.no': 'नहीं',
    'common.all': 'सभी',
    'common.more': 'अधिक',
    'common.view': 'देखें',
    'common.details': 'विवरण',
    
    'splash.poweredBy': 'फिटोंजे प्राइवेट लिमिटेड द्वारा संचालित',
    
    'resume.title': 'अपना रिज्यूमे बनाएं',
    'resume.buildResume': 'अपना रिज्यूमे बनाएं',
    'resume.uploadPhoto': 'फोटो अपलोड करें',
    'resume.changePhoto': 'फोटो बदलें',
    'resume.resume': 'रिज्यूमे',
    'resume.name': 'नाम',
    'resume.email': 'ईमेल',
    'resume.phone': 'फोन',
    'resume.experience': 'अनुभव',
    'resume.desiredRole': 'वांछित भूमिका',
    'resume.bio': 'परिचय',
    'resume.finalDetails': 'अंतिम विवरण',
    'resume.saveResume': 'रिज्यूमे सहेजें',
    'resume.selectRole': 'भूमिका चुनें',
    'resume.enterBio': 'अपना परिचय दर्ज करें',
    'resume.years': 'वर्ष',
    
    'jobs.findJobs': 'नौकरियां खोजें',
    'jobs.filterJobs': 'नौकरियों को फ़िल्टर करें',
    'jobs.searchJobs': 'नौकरियों के लिए खोजें...',
    'jobs.allJobs': 'सभी नौकरियां',
    'jobs.nearby': 'पास की',
    'jobs.salaryRange': 'वेतन सीमा',
    'jobs.experience': 'अनुभव',
    'jobs.expereinceRequired': 'आवश्यक अनुभव',
    'jobs.applyNow': 'अभी आवेदन करें',
    'jobs.jobDetails': 'नौकरी विवरण',
    'jobs.companyName': 'कंपनी का नाम',
    'jobs.location': 'स्थान',
    'jobs.salary': 'वेतन',
    'jobs.jobType': 'नौकरी का प्रकार',
    'jobs.fullTime': 'पूर्णकालिक',
    'jobs.partTime': 'अंशकालिक',
    'jobs.contract': 'अनुबंध',
    'jobs.noJobs': 'कोई नौकरी नहीं मिली',
    'jobs.loadingJobs': 'नौकरियां लोड हो रही हैं...',
    'jobs.shopDetails': 'दुकान विवरण',
    'jobs.viewMore': 'और देखें',
    'jobs.viewLess': 'कम देखें',
    'jobs.contactOwner': 'मालिक से संपर्क करें',
    'jobs.shareContact': 'संपर्क साझा करें',
    'jobs.contactShared': 'संपर्क साझा किया गया',
    'jobs.contactCredits': 'संपर्क क्रेडिट',
    'jobs.buyCredits': 'क्रेडिट खरीदें',
    'jobs.availableCredits': 'उपलब्ध क्रेडिट',
    'jobs.noCredits': 'अपर्याप्त क्रेडिट',
    'jobs.needCredits': 'संपर्क जानकारी देखने के लिए आपको क्रेडिट की आवश्यकता है',
    'jobs.subscribe': 'सदस्यता लें',
    'jobs.unlimited': 'असीमित एक्सेस',
    'jobs.applied': 'आवेदन किया',
    'jobs.applyUnlimited': 'असीमित नौकरियों के लिए आवेदन करें',
    
    'results.jobResults': 'नौकरी परिणाम',
    'results.yourApplications': 'आपके आवेदन',
    'results.applicantDetails': 'आवेदक विवरण',
    'results.viewProfile': 'प्रोफाइल देखें',
    'results.contactApplicant': 'आवेदक से संपर्क करें',
    
    'subscription.upgradeTitle': 'प्रीमियम में अपग्रेड करें',
    'subscription.choosePlan': 'अपनी योजना चुनें',
    'subscription.employerPlans': 'नियोक्ता योजनाएं',
    'subscription.basicPlan': 'बेसिक योजना',
    'subscription.premiumPlan': 'प्रीमियम योजना',
    'subscription.getVerified': 'सत्यापित बैज प्राप्त करें',
    'subscription.unlimitedApps': 'असीमित आवेदन',
    'subscription.priority': 'प्राथमिकता समर्थन',
    'subscription.monthly': 'मासिक',
    'subscription.yearly': 'वार्षिक',
    'subscription.features': 'विशेषताएं',
    'subscription.selectPlan': 'योजना चुनें',
    'subscription.subscribe': 'सदस्यता लें',
    
    'verify.getVerifiedBadge': 'सत्यापित बैज प्राप्त करें',
    'verify.paymentProcess': 'भुगतान प्रक्रिया',
    'verify.step1': '1. हमारी टीम आपके भुगतान स्क्रीनशॉट को सत्यापित करती है',
    'verify.step2': '2. सत्यापित बैज आपकी प्रोफाइल पर सक्रिय होता है',
    'verify.step3': '3. बैज आपकी सभी नौकरी पोस्ट पर दिखाई देता है',
    'verify.step4': '4. अनुमोदित होने पर आपको एक सूचना मिलती है',
    'verify.clickUpload': 'स्क्रीनशॉट अपलोड करने के लिए क्लिक करें',
    'verify.completePayment': 'भुगतान पूरा करें',
    'verify.amount': 'राशि',
    'verify.upiMethods': 'GPay, PhonePe, Paytm, कोई भी UPI',
    'verify.paymentScreenshot': 'भुगतान स्क्रीनशॉट',
    'verify.uploadScreenshot': 'स्क्रीनशॉट अपलोड करें',
    
    'profile.myProfile': 'मेरी प्रोफाइल',
    'profile.editProfile': 'प्रोफाइल संपादित करें',
    'profile.accountSettings': 'खाता सेटिंग्स',
    'profile.changePhoto': 'फोटो बदलें',
    'profile.dateOfBirth': 'जन्मतिथि',
    'profile.location': 'स्थान',
    'profile.experience': 'अनुभव',
    'profile.bio': 'परिचय',
    'profile.email': 'ईमेल',
    'profile.phone': 'फोन',
    'profile.emailCannotChanged': 'ईमेल नहीं बदला जा सकता',
    'profile.savedJobs': 'सहेजी गई नौकरियां',
    'profile.favoriteJobs': 'पसंदीदा नौकरियां',
    'profile.applications': 'आवेदन',
    'profile.preferences': 'प्राथमिकताएं',
    'profile.verified': 'सत्यापित',
    'profile.getVerified': 'सत्यापित करें',
    'profile.joinDate': 'शामिल होने की तारीख',
    'profile.viewResume': 'रिज्यूमे देखें',
    'profile.changePassword': 'पासवर्ड बदलें',
    'profile.twoFactor': 'दो-फैक्टर प्रमाणीकरण',
    'profile.privacy': 'गोपनीयता',
    'profile.notifications': 'सूचनाएं',
    
    'messages.messages': 'संदेश',
    'messages.chats': 'बातचीत',
    'messages.noMessages': 'कोई संदेश नहीं',
    'messages.startConversation': 'एक बातचीत शुरू करें',
    'messages.typeMessage': 'अपना संदेश टाइप करें...',
    'messages.sendMessage': 'संदेश भेजें',
    'messages.recentChats': 'हाल की बातचीत',
    'messages.search': 'संदेशों को खोजें...',
    'messages.online': 'ऑनलाइन',
    'messages.offline': 'ऑफलाइन',
    'messages.typing': 'टाइप कर रहे हैं...',
    'messages.blockedUser': 'अवरुद्ध उपयोगकर्ता',
    'messages.blockUser': 'उपयोगकर्ता को अवरुद्ध करें',
    'messages.unblock': 'अनब्लॉक करें',
    'messages.delete': 'चैट हटाएं',
    'messages.markAsRead': 'पढ़ा हुआ चिह्नित करें',
    'messages.markAsUnread': 'अपढ़ चिह्नित करें',
    'messages.clearChat': 'चैट साफ करें',
    'messages.call': 'कॉल करें',
    'messages.video': 'वीडियो कॉल',
    
    'notifications.title': 'सूचनाएं',
    'notifications.unread': 'अपढ़',
    'notifications.markAllRead': 'सभी को पढ़ा हुआ चिह्नित करें',
    'notifications.noNotifications': 'कोई सूचना नहीं',
    'notifications.applicationReceived': 'आवेदन प्राप्त हुआ',
    'notifications.newJobPosted': 'नई नौकरी पोस्ट की गई',
    'notifications.profileViewed': 'प्रोफाइल देखा गया',
    'notifications.messageReceived': 'नया संदेश',
    'notifications.jobAlert': 'नौकरी सूचना',
    'notifications.applicationStatus': 'आवेदन स्थिति अपडेट की गई',
    'notifications.contactShared': 'संपर्क साझा किया गया',
    'notifications.creditsAdded': 'क्रेडिट जोड़े गए',
    'notifications.verificationApproved': 'सत्यापन अनुमोदित',
    
    'aboutUs.aboutUs': 'हमारे बारे में',
    'aboutUs.title': 'फिटोंजे प्राइवेट लिमिटेड',
    'aboutUs.tagline': 'सौंदर्य उद्योग में शीर्ष प्रतिभा से जुड़ें',
    'aboutUs.vision': 'हमारा दृष्टिकोण',
    'aboutUs.visionDescription': 'सुंदरता और कल्याण उद्योग में प्रतिभाशाली पेशेवरों और शीर्ष सैलूनों को जोड़ने में क्रांति लाना',
    'aboutUs.mission': 'हमारा मिशन',
    'aboutUs.missionDescription': 'सुंदरता पेशेवरों और सैलून मालिकों को सफल करियर और संपन्न व्यवसाय बनाने में सशक्त बनाना',
    'aboutUs.values': 'हमारे मूल्य',
    'aboutUs.value1': 'उत्कृष्टता',
    'aboutUs.value2': 'सत्यनिष्ठा',
    'aboutUs.value3': 'नवाचार',
    'aboutUs.value4': 'समुदाय',
    'aboutUs.features': 'हमें क्यों चुनें',
    'aboutUs.feature1': 'आसान नौकरी मिलान',
    'aboutUs.feature2': 'सत्यापित पेशेवर',
    'aboutUs.feature3': '24/7 समर्थन',
    'aboutUs.feature4': 'सुरक्षित भुगतान',
    'aboutUs.contactUs': 'संपर्क में रहें',
    'aboutUs.email': 'ईमेल',
    'aboutUs.phone': 'फोन',
    'aboutUs.address': 'पता',
    'aboutUs.followUs': 'हमारा अनुसरण करें',
    'aboutUs.termsOfService': 'सेवा की शर्तें',
    'aboutUs.privacyPolicy': 'गोपनीयता नीति',
    'aboutUs.contactSupport': 'समर्थन से संपर्क करें',
    
    'job.createJob': 'नौकरी बनाएं',
    'job.postJob': 'नौकरी पोस्ट करें',
    'job.jobTitle': 'नौकरी का शीर्षक',
    'job.jobDescription': 'नौकरी विवरण',
    'job.location': 'स्थान',
    'job.salary': 'वेतन',
    'job.salaryRange': 'वेतन सीमा',
    'job.jobType': 'नौकरी का प्रकार',
    'job.experience': 'आवश्यक अनुभव',
    'job.requiredSkills': 'आवश्यक कौशल',
    'job.benefits': 'लाभ',
    'job.postJobButton': 'नौकरी पोस्ट करें',
    'job.editJob': 'नौकरी संपादित करें',
    'job.deleteJob': 'नौकरी हटाएं',
    'job.jobPosted': 'नौकरी सफलतापूर्वक पोस्ट की गई',
    'job.jobUpdated': 'नौकरी सफलतापूर्वक अपडेट की गई',
    'job.jobDeleted': 'नौकरी सफलतापूर्वक हटाई गई',
    'job.preview': 'पूर्वावलोकन',
    'job.draft': 'ड्राफ्ट के रूप में सहेजें',
    'job.publish': 'प्रकाशित करें',
    
    'owner.dashboard': 'डैशबोर्ड',
    'owner.activeJobs': 'सक्रिय नौकरियां',
    'owner.closedJobs': 'बंद नौकरियां',
    'owner.applicants': 'आवेदक',
    'owner.statistics': 'आंकड़े',
    'owner.viewApplications': 'आवेदन देखें',
    'owner.acceptApplication': 'स्वीकृत',
    'owner.rejectApplication': 'अस्वीकार करें',
    'owner.applicantInfo': 'आवेदक जानकारी',
    'owner.resume': 'रिज्यूमे',
    'owner.contactInfo': 'संपर्क जानकारी',
    'owner.sendOffer': 'ऑफर भेजें',
    'owner.scheduleInterview': 'साक्षात्कार शेड्यूल करें',
    'owner.makePayment': 'भुगतान करें',
    'owner.buyCredits': 'क्रेडिट खरीदें',
    
    'settings.settings': 'सेटिंग्स',
    'settings.accountSettings': 'खाता सेटिंग्स',
    'settings.privacySettings': 'गोपनीयता सेटिंग्स',
    'settings.notificationSettings': 'सूचना सेटिंग्स',
    'settings.preferenceSettings': 'प्राथमिकता सेटिंग्स',
    'settings.language': 'भाषा',
    'settings.darkMode': 'डार्क मोड',
    'settings.notifications': 'सूचनाएं',
    'settings.emailNotifications': 'ईमेल सूचनाएं',
    'settings.pushNotifications': 'पुश सूचनाएं',
    'settings.smsNotifications': 'एसएमएस सूचनाएं',
    'settings.privacy': 'गोपनीयता',
    'settings.profileVisibility': 'प्रोफाइल दृश्यमानता',
    'settings.showOnlineStatus': 'ऑनलाइन स्थिति दिखाएं',
    'settings.blockList': 'ब्लॉक सूची',
    'settings.twoFactor': 'दो-फैक्टर प्रमाणीकरण',
    'settings.changePassword': 'पासवर्ड बदलें',
    'settings.currentPassword': 'वर्तमान पासवर्ड',
    'settings.newPassword': 'नया पासवर्ड',
    'settings.confirmPassword': 'पासवर्ड की पुष्टि करें',
    'settings.logout': 'लॉगआउट',
    'settings.deleteAccount': 'खाता हटाएं',
    'settings.help': 'मदद और समर्थन',
    'settings.faq': 'अक्सर पूछे जाने वाले प्रश्न',
    'settings.contactSupport': 'समर्थन से संपर्क करें',
    'settings.about': 'बारे में',
    'settings.version': 'संस्करण',
    
    'credits.30Credits': '30 क्रेडिट',
    'credits.availableCredits': 'उपलब्ध क्रेडिट',
    'credits.buyCredits': 'संपर्क क्रेडिट खरीदें',
    'credits.creditUsed': 'क्रेडिट उपयोग किया गया',
    'credits.creditsRemaining': 'शेष क्रेडिट',
    'credits.lowCredits': 'कम क्रेडिट',
    'credits.outOfCredits': 'क्रेडिट समाप्त',
    
    'salon.completeSalonProfile': 'अपनी सैलून प्रोफाइल पूरी करें',
    'salon.salonName': 'सैलून का नाम',
    'salon.salonDescription': 'सैलून विवरण',
    'salon.salonAddress': 'सैलून का पता',
    'salon.salonPhone': 'सैलून फोन',
    'salon.salonEmail': 'सैलून ईमेल',
    'salon.salonWebsite': 'सैलून वेबसाइट',
    'salon.salonType': 'सैलून का प्रकार',
    'salon.services': 'दी जाने वाली सेवाएं',
    'salon.operatingHours': 'संचालन समय',
    'salon.uploadLogo': 'लोगो अपलोड करें',
    'salon.uploadCover': 'कवर फोटो अपलोड करें',
    'salon.saveSalonProfile': 'सैलून प्रोफाइल सहेजें',
    'salon.profileComplete': 'प्रोफाइल पूरी हुई',
    
    'message.success': 'सफलता!',
    'message.error': 'कुछ गलत हुआ',
    'message.pleaseWait': 'कृपया प्रतीक्षा करें...',
    'message.loading': 'लोड हो रहा है...',
    'message.noData': 'कोई डेटा उपलब्ध नहीं',
    'message.invalidEmail': 'अमान्य ईमेल पता',
    'message.passwordMismatch': 'पासवर्ड मेल नहीं खाते',
    'message.fillAllFields': 'कृपया सभी फील्ड भरें',
    'message.confirmDelete': 'क्या आप सुनिश्चित हैं?',
    'message.deleteConfirmed': 'सफलतापूर्वक हटाया गया',
  },
  
  Telugu: {
    'auth.title': 'తిరిగి స్వాగతం',
    'auth.createAccount': 'ఖాతా సృష్టించండి',
    'auth.signInSubtitle': 'కొనసాగించడానికి సైన్ ఇన్ చేయండి',
    'auth.signUpSubtitle': 'ప్రారంభించడానికి సైన్ అప్ చేయండి',
    'auth.signIn': 'సైన్ ఇన్ చేయి',
    'auth.signUp': 'సైన్ అప్ చేయి',
    'auth.email': 'ఇమెయిల్',
    'auth.password': 'పాస్‌వర్డ్',
    'auth.phone': 'ఫోన్ నంబర్',
    'auth.name': 'పూర్తి పేరు',
    'auth.forgotPassword': 'పాస్‌వర్డ్ మరిచిపోయారా?',
    'auth.dontHaveAccount': 'ఖాతా లేదు?',
    'auth.alreadyHaveAccount': 'ఇప్పటికే ఖాతా ఉందా?',
    'auth.rememberMe': 'నన్ను గుర్తుంచుకోండి',
    
    'role.selectRole': 'మీ పాత్రను ఎంచుకోండి',
    'role.jobSeeker': 'ఉద్యోగ చేసేవారు',
    'role.salonOwner': 'సెలూన్ యజమాని',
    'role.findJobs': 'ఉద్యోగాలు కనుగొనండి',
    'role.manageJobs': 'ఉద్యోగాలను నిర్వహించండి',
    'role.description1': 'సెలూన్ ఉద్యోగాల కోసం వెతకండి మరియు అప్లై చేయండి',
    'role.description2': 'ఉద్యోగ విండోలను పోస్ట్ చేసి నిర్వహించండి',
    'role.back': 'వెనుకకు',
    'role.next': 'తర్వాత',
    
    'nav.home': 'హోమ్',
    'nav.jobs': 'ఉద్యోగాలు',
    'nav.messages': 'సందేశాలు',
    'nav.chats': 'చాట్‌లు',
    'nav.notifications': 'నోటిఫికేషన్‌లు',
    'nav.profile': 'ప్రోఫైల్',
    'nav.settings': 'సెట్టింగ్‌లు',
    'nav.about': 'ჩვენს గახ',
    'nav.dashboard': 'డ్యాష్‌బోర్డ్',
    'nav.postJob': 'ఉద్యోగం పోస్ట్ చేయండి',
    'owner.manageJobs': 'ఉద్యోగాలను నిర్వహించండి',
    'job.createJob': 'ఉద్యోగం సృష్టించండి',
    
    'common.save': 'సేవ్ చేయండి',
    'common.cancel': 'రద్దు చేయండి',
    'common.delete': 'తొలగించండి',
    'common.edit': 'సవరించండి',
    'common.loading': 'లోడ్ చేస్తోంది...',
    'common.error': 'ఎర్రర్',
    'common.success': 'సఫలం',
    'common.back': 'వెనుకకు',
    'common.next': 'తర్వాత',
    'common.remember': 'గుర్తుంచుకోండి',
    'common.submit': 'సమర్పించండి',
    'common.logout': 'లాగ్‌అవుట్',
    'common.close': 'మూసివేయండి',
    'common.search': 'వెతకండి',
    'common.filter': 'ఫిల్టర్',
    'common.apply': 'అప్లై చేయండి',
    'common.send': 'పంపండి',
    'common.message': 'సందేశం',
    'common.call': 'కాల్ చేయండి',
    'common.continue': 'కొనసాగించండి',
    'common.skip': 'దాటవేయండి',
    'common.download': 'డౌన్‌లోడ్ చేయండి',
    'common.upload': 'అప్‌లోడ్ చేయండి',
    'common.change': 'మార్చండి',
    'common.confirm': 'నిర్ధారించండి',
    'common.yes': 'అవును',
    'common.no': 'కాదు',
    'common.all': 'అన్నీ',
    'common.more': 'మరిన్ని',
    'common.view': 'చూడండి',
    'common.details': 'వివరాలు',
    
    'splash.poweredBy': 'ఫిటోంజ్ ప్రైవేట్ లిమిటెడ్ ద్వారా శక్తిచేసిన',
    
    'resume.title': 'మీ రిజ్యూమ్ సృష్టించండి',
    'resume.buildResume': 'మీ రిజ్యూమ్ సృష్టించండి',
    'resume.uploadPhoto': 'ఫోటో అప్‌లోడ్ చేయండి',
    'resume.changePhoto': 'ఫోటో మార్చండి',
    'resume.resume': 'రిజ్యూమ్',
    'resume.name': 'పేరు',
    'resume.email': 'ఇమెయిల్',
    'resume.phone': 'ఫోన్',
    'resume.experience': 'అనుభవం',
    'resume.desiredRole': 'కోరిన పాత్ర',
    'resume.bio': 'బయో',
    'resume.finalDetails': 'తుది వివరాలు',
    'resume.saveResume': 'రిజ్యూమ్ సేవ్ చేయండి',
    'resume.selectRole': 'పాత్రను ఎంచుకోండి',
    'resume.enterBio': 'మీ బయో నమోదు చేయండి',
    'resume.years': 'సంవత్సరాలు',
    
    'jobs.findJobs': 'ఉద్యోగాలు కనుగొనండి',
    'jobs.filterJobs': 'ఉద్యోగాలను ఫిల్టర్ చేయండి',
    'jobs.searchJobs': 'ఉద్యోగాల కోసం వెతకండి...',
    'jobs.allJobs': 'అన్ని ఉద్యోగాలు',
    'jobs.nearby': 'సమీపలో',
    'jobs.salaryRange': 'జీతం పరిధి',
    'jobs.experience': 'అనుభవం',
    'jobs.expereinceRequired': 'అవసరమైన అనుభవం',
    'jobs.applyNow': 'ఇప్పుడు అప్లై చేయండి',
    'jobs.jobDetails': 'ఉద్యోగ వివరాలు',
    'jobs.companyName': 'సంస్థ పేరు',
    'jobs.location': 'స్థానం',
    'jobs.salary': 'జీతం',
    'jobs.jobType': 'ఉద్యోగ రకం',
    'jobs.fullTime': 'పూర్ణకాలీन',
    'jobs.partTime': 'అర్ధకాలీన',
    'jobs.contract': 'ఒప్పందం',
    'jobs.noJobs': 'ఉద్యోగాలు కనుగొనబడలేదు',
    'jobs.loadingJobs': 'ఉద్యోగాలు లోడ్ చేస్తోంది...',
    'jobs.shopDetails': 'దుకాణ వివరాలు',
    'jobs.viewMore': 'మరిన్ని చూడండి',
    'jobs.viewLess': 'తక్కువ చూడండి',
    'jobs.contactOwner': 'యజమానిని సంప్రదించండి',
    'jobs.shareContact': 'సంప్రదింపు భాగస్వామ్యం చేయండి',
    'jobs.contactShared': 'సంప్రదింపు భాగస్వామ్యం చేయబడింది',
    'jobs.contactCredits': 'సంప్రదింపు క్రెడిట్‌లు',
    'jobs.buyCredits': 'క్రెడిట్‌లను కొనండి',
    'jobs.availableCredits': 'అందుబాటులో ఉన్న క్రెడిట్‌లు',
    'jobs.noCredits': 'అసంపూర్ణ క్రెడిట్‌లు',
    'jobs.needCredits': 'సంప్రదింపు సమాచారాన్ని చూడటానికి మీకు క్రెడిట్‌లు అవసరం',
    'jobs.subscribe': 'సబ్‌స్క్రైబ్ చేయండి',
    'jobs.unlimited': 'అపరిమిత యాక్సెస్',
    'jobs.applied': 'అప్లై చేసిన',
    'jobs.applyUnlimited': 'అపరిమిత ఉద్యోగాలకు అప్లై చేయండి',
    
    'results.jobResults': 'ఉద్యోగ ఫలితాలు',
    'results.yourApplications': 'మీ అరજీలు',
    'results.applicantDetails': 'దరఖాస్తుదారు వివరాలు',
    'results.viewProfile': 'ప్రోఫైల్ చూడండి',
    'results.contactApplicant': 'దరఖాస్తుదారిని సంప్రదించండి',
    
    'subscription.upgradeTitle': 'ప్రీమియంకు అపగ్రేడ్ చేయండి',
    'subscription.choosePlan': 'మీ ప్లాన్‌ను ఎంచుకోండి',
    'subscription.employerPlans': 'యోజక ప్లాన్‌లు',
    'subscription.basicPlan': 'ప్రాథమిక ప్లాన్',
    'subscription.premiumPlan': 'ప్రీమియం ప్లాన్',
    'subscription.getVerified': 'ధృవీకృత బ్యాడ్జ్ పొందండి',
    'subscription.unlimitedApps': 'అపరిమిత అరజీలు',
    'subscription.priority': 'ప్రాధాన్యత సపోర్టు',
    'subscription.monthly': 'నెలవారీ',
    'subscription.yearly': 'సంవత్సరానికి',
    'subscription.features': 'లక్షణాలు',
    'subscription.selectPlan': 'ప్లాన్‌ను ఎంచుకోండి',
    'subscription.subscribe': 'సబ్‌స్క్రైబ్ చేయండి',
    
    'verify.getVerifiedBadge': 'ధృవీకృత బ్యాడ్జ్ పొందండి',
    'verify.paymentProcess': 'చెల్లింపు ప్రక్రియ',
    'verify.step1': '1. మా జట్టు మీ చెల్లింపు స్క్రీన్‌షాట్‌ను ధృవీకరిస్తుంది',
    'verify.step2': '2. ధృవీకృత బ్యాడ్జ్ మీ ప్రోఫైల్‌పై సక్రియీకరించబడింది',
    'verify.step3': '3. బ్యాడ్జ్ మీ అన్ని ఉద్యోగ పోస్ట్‌లపై కనిపిస్తుంది',
    'verify.step4': '4. ఆమోదించిన తర్వాత మీరు ఉ告్ఞప్తిని అందుకుంటారు',
    'verify.clickUpload': 'స్క్రీన్‌షాట్ అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి',
    'verify.completePayment': 'చెల్లింపు సంపూర్ణం చేయండి',
    'verify.amount': 'మొత్తం',
    'verify.upiMethods': 'GPay, PhonePe, Paytm, ఏదైనా UPI',
    'verify.paymentScreenshot': 'చెల్లింపు స్క్రీన్‌షాట్',
    'verify.uploadScreenshot': 'స్క్రీన్‌షాట్ అప్‌లోడ్ చేయండి',
    
    'profile.myProfile': 'నా ప్రోఫైల్',
    'profile.editProfile': 'ప్రోఫైల్‌ను సవరించండి',
    'profile.accountSettings': 'ఖాతా సెట్టింగ్‌లు',
    'profile.changePhoto': 'ఫోటో మార్చండి',
    'profile.dateOfBirth': 'పుట్టిన తేదీ',
    'profile.location': 'స్థానం',
    'profile.experience': 'అనుభవం',
    'profile.bio': 'బయో',
    'profile.email': 'ఇమెయిల్',
    'profile.phone': 'ఫోన్',
    'profile.emailCannotChanged': 'ఇమెయిల్‌ను మార్చలేము',
    'profile.savedJobs': 'సేవ్ చేసిన ఉద్యోగాలు',
    'profile.favoriteJobs': 'ఇష్టమైన ఉద్యోగాలు',
    'profile.applications': 'అరజీలు',
    'profile.preferences': 'ప్రాధాన్యతలు',
    'profile.verified': 'ధృవీకృత',
    'profile.getVerified': 'ధృవీకృతం పొందండి',
    'profile.joinDate': 'చేరిన తేదీ',
    'profile.viewResume': 'రిజ్యూమ్ చూడండి',
    'profile.changePassword': 'పాస్‌వర్డ్ మార్చండి',
    'profile.twoFactor': 'రెండు-ఫ్యాక్టర్ ప్రమాణీకరణ',
    'profile.privacy': 'గోపనీయత',
    'profile.notifications': 'నోటిఫికేషన్‌లు',
    
    'messages.messages': 'సందేశాలు',
    'messages.chats': 'చాట్‌లు',
    'messages.noMessages': 'సందేశాలు లేవు',
    'messages.startConversation': 'సంభాషణను ప్రారంభించండి',
    'messages.typeMessage': 'మీ సందేశాన్ని టైప్ చేయండి...',
    'messages.sendMessage': 'సందేశం పంపండి',
    'messages.recentChats': 'ఇటీవలి చాట్‌లు',
    'messages.search': 'సందేశాల కోసం వెతకండి...',
    'messages.online': 'ఆన్‌లైన్',
    'messages.offline': 'ఆఫ్‌లైన్',
    'messages.typing': 'టైప్ చేస్తోంది...',
    'messages.blockedUser': 'బ్లాక్ చేసిన వినియోగదారు',
    'messages.blockUser': 'వినియోగదారుని బ్లాక్ చేయండి',
    'messages.unblock': 'అన్‌బ్లాక్ చేయండి',
    'messages.delete': 'చాట్ తొలగించండి',
    'messages.markAsRead': 'చదివిన విధంగా చిహ్నించండి',
    'messages.markAsUnread': 'చదవని విధంగా చిహ్నించండి',
    'messages.clearChat': 'చాట్ క్లియర్ చేయండి',
    'messages.call': 'కాల్ చేయండి',
    'messages.video': 'వీడియో కాల్',
    
    'notifications.title': 'నోటిఫికేషన్‌లు',
    'notifications.unread': 'చదువని',
    'notifications.markAllRead': 'అన్నిటిని చదివిన విధంగా చిహ్నించండి',
    'notifications.noNotifications': 'నోటిఫికేషన్‌లు లేవు',
    'notifications.applicationReceived': 'అరజీ స్వీకరించబడింది',
    'notifications.newJobPosted': 'కొత్త ఉద్యోగం పోస్ట్ చేయబడింది',
    'notifications.profileViewed': 'ప్రోఫైల్ చూశారు',
    'notifications.messageReceived': 'కొత్త సందేశం',
    'notifications.jobAlert': 'ఉద్యోగ అలర్ట్',
    'notifications.applicationStatus': 'అరజీ స్థితి అపడేట్ చేయబడింది',
    'notifications.contactShared': 'సంప్రదింపు భాగస్వామ్యం చేయబడింది',
    'notifications.creditsAdded': 'క్రెడిట్‌లు జోడించబడ్డాయి',
    'notifications.verificationApproved': 'ధృవీకరణ ఆమోదించబడింది',
    
    'aboutUs.aboutUs': 'ჩვენს గახ',
    'aboutUs.title': 'ఫిటోంజ్ ప్రైవేట్ లిమిటెడ్',
    'aboutUs.tagline': 'సBeauty్ beauty ఇండస్ట్రీలో అగ్ర ప్రతిభకు కనెక్ట్ చేయండి',
    'aboutUs.vision': 'మా దృష్టి',
    'aboutUs.visionDescription': 'సrown్యత మరియు wellness్యలక్ష్మ్య ఇండస్ట్రీలో ప్రతిభాశీల నిపుణులను ఎగ్రహమైన సెలూన్‌లకు కనెక్ట్ చేయడం ద్వారా విప్లవం సంపాదించుకోవటం',
    'aboutUs.mission': 'మా లక్ష్యం',
    'aboutUs.missionDescription': 'Beauty్ beauty నిపుణులను మరియు సెలూన్ యజమానులను సఫల కెరీర్లు మరియు সమృద్ధ వ్యవసాయాలను నిర్మించటానికి అధికారం',
    'aboutUs.values': 'మా విలువలు',
    'aboutUs.value1': 'ఉత్కర్ష్టత',
    'aboutUs.value2': 'సততangers',
    'aboutUs.value3': 'ఆవిష్కారం',
    'aboutUs.value4': 'సమాజం',
    'aboutUs.features': 'ఎందుకు ఆమన్ని ఎంచుకోండి',
    'aboutUs.feature1': 'సులభ ఉద్యోగ సరిపోలిక',
    'aboutUs.feature2': 'ధృవీకృత నిపుణులు',
    'aboutUs.feature3': '24/7 సపోర్టు',
    'aboutUs.feature4': 'సురక్షిత చెల్లింపులు',
    'aboutUs.contactUs': 'మాకు సంప్రదించండి',
    'aboutUs.email': 'ఇమెయిల్',
    'aboutUs.phone': 'ఫోన్',
    'aboutUs.address': 'చిరునామా',
    'aboutUs.followUs': 'మాన్ని అనుసరించండి',
    'aboutUs.termsOfService': 'సేవ నిబంధనలు',
    'aboutUs.privacyPolicy': 'గోపనీయత విధానం',
    'aboutUs.contactSupport': 'సపోర్టుని సంప్రదించండి',
    
    'job.createJob': 'ఉద్యోగం సృష్టించండి',
    'job.postJob': 'ఉద్యోగం పోస్ట్ చేయండి',
    'job.jobTitle': 'ఉద్యోగ శీర్షిక',
    'job.jobDescription': 'ఉద్యోగ వివరణ',
    'job.location': 'స్థానం',
    'job.salary': 'జీతం',
    'job.salaryRange': 'జీతం పరిధి',
    'job.jobType': 'ఉద్యోగ రకం',
    'job.experience': 'అవసరమైన అనుభవం',
    'job.requiredSkills': 'అవసరమైన నైపుణ్యాలు',
    'job.benefits': 'ప్రయోజనాలు',
    'job.postJobButton': 'ఉద్యోగం పోస్ట్ చేయండి',
    'job.editJob': 'ఉద్యోగాన్ని సవరించండి',
    'job.deleteJob': 'ఉద్యోగాన్ని తొలగించండి',
    'job.jobPosted': 'ఉద్యోగం విజయవంతంగా పోస్ట్ చేయబడింది',
    'job.jobUpdated': 'ఉద్యోగం విజయవంతంగా అపడేట్ చేయబడింది',
    'job.jobDeleted': 'ఉద్యోగం విజయవంతంగా తొలగించబడింది',
    'job.preview': 'ఉదాహరణ',
    'job.draft': 'డ్రాఫ్ట్‌గా సేవ్ చేయండి',
    'job.publish': 'ప్రచురించండి',
    
    'owner.dashboard': 'డ్యాష్‌బోర్డ్',
    'owner.activeJobs': 'క్రియాశీల ఉద్యోగాలు',
    'owner.closedJobs': 'మూసిన ఉద్యోగాలు',
    'owner.applicants': 'దరఖాస్తుదారులు',
    'owner.statistics': 'గణాంకాలు',
    'owner.viewApplications': 'అరజీలను చూడండి',
    'owner.acceptApplication': 'ఆమోదించండి',
    'owner.rejectApplication': 'తిరస్కరించండి',
    'owner.applicantInfo': 'దరఖాస్తుదారు సమాచారం',
    'owner.resume': 'రిజ్యూమ్',
    'owner.contactInfo': 'సంప్రదింపు సమాచారం',
    'owner.sendOffer': 'అందించండి పంపండి',
    'owner.scheduleInterview': 'ఇంటర్వ్యూ షెడ్యూల్ చేయండి',
    'owner.makePayment': 'చెల్లింపు చేయండి',
    'owner.buyCredits': 'క్రెడిట్‌లను కొనండి',
    
    'settings.settings': 'సెట్టింగ్‌లు',
    'settings.accountSettings': 'ఖాతా సెట్టింగ్‌లు',
    'settings.privacySettings': 'గోపనీయత సెట్టింగ్‌లు',
    'settings.notificationSettings': 'నోటిఫికేషన్ సెట్టింగ్‌లు',
    'settings.preferenceSettings': 'ప్రాధాన్యత సెట్టింగ్‌లు',
    'settings.language': 'భాష',
    'settings.darkMode': 'డార్క్ మోడ్',
    'settings.notifications': 'నోటిఫికేషన్‌లు',
    'settings.emailNotifications': 'ఇమెయిల్ నోటిఫికేషన్‌లు',
    'settings.pushNotifications': 'పుష్ నోటిఫికేషన్‌లు',
    'settings.smsNotifications': 'SMS నోటిఫికేషన్‌లు',
    'settings.privacy': 'గోపనీయత',
    'settings.profileVisibility': 'ప్రోఫైల్ దృశ్యమానత',
    'settings.showOnlineStatus': 'ఆన్‌లైన్ స్థితిని చూపండి',
    'settings.blockList': 'బ్లాక్ జాబితా',
    'settings.twoFactor': 'రెండు-ఫ్యాక్టర్ ప్రమాణీకరణ',
    'settings.changePassword': 'పాస్‌వర్డ్ మార్చండి',
    'settings.currentPassword': 'ప్రస్తుత పాస్‌వర్డ్',
    'settings.newPassword': 'కొత్త పాస్‌వర్డ్',
    'settings.confirmPassword': 'పాస్‌వర్డ్‌ను నిర్ధారించండి',
    'settings.logout': 'లాగ్‌అవుట్',
    'settings.deleteAccount': 'ఖాతాను తొలగించండి',
    'settings.help': 'సహాయం మరియు సపోర్టు',
    'settings.faq': 'FAQ',
    'settings.contactSupport': 'సపోర్టుని సంప్రదించండి',
    'settings.about': 'గురించి',
    'settings.version': 'సంస్కరణ',
    
    'credits.30Credits': '30 క్రెడిట్‌లు',
    'credits.availableCredits': 'అందుబాటులో ఉన్న క్రెడిట్‌లు',
    'credits.buyCredits': 'సంప్రదింపు క్రెడిట్‌లను కొనండి',
    'credits.creditUsed': 'ఉపయోగించిన క్రెడిట్',
    'credits.creditsRemaining': 'మిగిలిన క్రెడిట్‌లు',
    'credits.lowCredits': 'తక్కువ క్రెడిట్‌లు',
    'credits.outOfCredits': 'క్రెడిట్‌లు అయిపోయాయి',
    
    'salon.completeSalonProfile': 'మీ సెలూన్ ప్రోఫైల్‌ను పూర్ణం చేయండి',
    'salon.salonName': 'సెలూన్ పేరు',
    'salon.salonDescription': 'సెలూన్ వివరణ',
    'salon.salonAddress': 'సెలూన్ చిరునామా',
    'salon.salonPhone': 'సెలూన్ ఫోన్',
    'salon.salonEmail': 'సెలూన్ ఇమెయిల్',
    'salon.salonWebsite': 'సెలూన్ వెబ్‌సైట్',
    'salon.salonType': 'సెలూన్ రకం',
    'salon.services': 'అందించిన సేవలు',
    'salon.operatingHours': 'పనిచేసే సమయం',
    'salon.uploadLogo': 'లోగో అప్‌లోడ్ చేయండి',
    'salon.uploadCover': 'కవర్ ఫోటో అప్‌లోడ్ చేయండి',
    'salon.saveSalonProfile': 'సెలూన్ ప్రోఫైల్ సేవ్ చేయండి',
    'salon.profileComplete': 'ప్రోఫైల్ సంపూర్ణం',
    
    'message.success': 'విజయం!',
    'message.error': 'ఏదో సరికాని జరిగింది',
    'message.pleaseWait': 'దయచేసి ఎదిరండి...',
    'message.loading': 'లోడ్ చేస్తోంది...',
    'message.noData': 'డేటా లేదు',
    'message.invalidEmail': 'చెల్లని ఇమెయిల్ చిరునామా',
    'message.passwordMismatch': 'పాస్‌వర్డ్‌లు సరిపోలవు',
    'message.fillAllFields': 'దయచేసి అన్ని ఫీల్డ్‌లను పూరించండి',
    'message.confirmDelete': 'మీరు సుమారుగా ఉన్నారా?',
    'message.deleteConfirmed': 'విజయవంతంగా తొలగించబడింది',
  },

  // I'll add Tamil, Kannada, Gujarati, Malayalam, Marathi, and Urdu translations similarly...
  // For brevity, showing structure but adding the key languages
  
  Tamil: {
    'auth.title': 'மீண்டும் வரவேற்கிறோம்',
    'auth.createAccount': 'கணக்கு உருவாக்கவும்',
    'auth.signInSubtitle': 'தொடர சைன் இன் செய்யவும்',
    'auth.signUpSubtitle': 'தொடங்க சைன் அப் செய்யவும்',
    'auth.signIn': 'சைன் இன்',
    'auth.signUp': 'சைன் அப்',
    'auth.email': 'ஈமெயில்',
    'auth.password': 'கடவுசொல்',
    'auth.phone': 'ფოन் எண்',
    'auth.name': 'முழு பெயர்',
    'auth.forgotPassword': 'கடவுசொல் மறந்துவிட்டீர்களா?',
    'auth.dontHaveAccount': 'கணக்கு இல்லையா?',
    'auth.alreadyHaveAccount': 'ஏற்கனவே கணக்கு உள்ளதா?',
    'auth.rememberMe': 'என்னை நினைவில் வைக்க',
    
    'nav.home': 'வீடு',
    'nav.jobs': 'வேலைகள்',
    'nav.messages': 'செய்திகள்',
    'nav.chats': 'உரையாடல்கள்',
    'nav.notifications': 'அறிவிப்புகள்',
    'nav.profile': 'சுயவிவரம்',
    'nav.settings': 'அமைப்புகள்',
    'nav.about': 'எங்களைப் பற்றி',
    'nav.dashboard': '대시보드',
    'nav.postJob': 'வேலை போஸ்ட் செய்க',
    'owner.manageJobs': 'வேலைகளை நிர்வகிக்க',
    'job.createJob': 'வேலை உருவாக்கவும்',
    
    'common.save': 'சேமிக்கவும்',
    'common.cancel': 'ரத்து செய்க',
    'common.delete': 'அழிக்கவும்',
    'common.edit': 'திருத்தவும்',
    'common.loading': 'சுமைகிறது...',
    'common.error': 'பிழை',
    'common.success': 'வெற்றி',
    'common.back': 'பின்னால்',
    'common.next': 'அடுத்தது',
    'common.remember': 'நினைவில் வைக்க',
    'common.submit': 'சமர்பிக்கவும்',
    'common.logout': 'வெளியேறுக',
    'common.close': 'மூடவும்',
    'common.search': 'தேடவும்',
    'common.filter': 'வடிப்பி',
    'common.apply': 'விண்ணப்பிக்கவும்',
    'common.send': 'அனுப்பவும்',
    'common.message': 'செய்தி',
    'common.call': 'அழைக்கவும்',
    'common.continue': 'தொடரவும்',
    'common.skip': 'தவிர்க்கவும்',
    'common.download': 'பதிவிறக்கவும்',
    'common.upload': 'பதிவேற்றவும்',
    'common.change': 'மாற்றவும்',
    'common.confirm': 'உறுதிப்படுத்தவும்',
    'common.yes': 'ஆம்',
    'common.no': 'இல்லை',
    'common.all': 'அனைத்தும்',
    'common.more': 'மேலும்',
    'common.view': 'பார்க்கவும்',
    'common.details': 'விவரங்கள்',
    
    'jobs.findJobs': 'வேலைகளைக் கண்டுபிடிக்கவும்',
    'jobs.filterJobs': 'வேலைகளை வடிகட்டவும்',
    'jobs.searchJobs': 'வேலைகளைத் தேடவும்...',
    'jobs.allJobs': 'அனைத்து வேலைகளும்',
    'jobs.nearby': 'அருகாமை',
    'jobs.applyNow': 'இப்போது விண்ணப்பிக்கவும்',
    'jobs.availableCredits': 'கிடைக்கும் வரவுகள்',
    'jobs.noCredits': 'போதுமான வரவுகள் இல்லை',
    'jobs.applied': 'விண்ணப்பிக்கப்பட்ட',
    
    'profile.myProfile': 'எனது சுயவிவரம்',
    'profile.editProfile': 'சுயவிவரத்தைத் திருத்தவும்',
    'profile.dateOfBirth': 'பிறந்த தேதி',
    'profile.location': 'இடம்',
    'profile.experience': 'அனுபவம்',
    'profile.bio': 'உயிரியல்',
    'profile.verified': 'சரிபார்க்கப்பட்ட',
    
    'messages.messages': 'செய்திகள்',
    'messages.chats': 'உரையாடல்கள்',
    'messages.noMessages': 'செய்திகள் இல்லை',
    'messages.typeMessage': 'உங்கள் செய்தியை தட்டச்சு செய்யவும்...',
    'messages.sendMessage': 'செய்தி அனுப்பவும்',
    
    'notifications.title': 'அறிவிப்புகள்',
    'notifications.unread': 'படிக்கப்படாத',
    'notifications.markAllRead': 'அனைத்தையும் படித்தவை என்று குறிக்கவும்',
    'notifications.noNotifications': 'அறிவிப்புகள் இல்லை',
    
    'settings.settings': 'அமைப்புகள்',
    'settings.language': 'மொழி',
    'settings.darkMode': 'இருண்ட பயன்முறை',
    'settings.logout': 'வெளியேறுக',
    
    'message.success': 'வெற்றி!',
    'message.error': 'ஏதாவது தவறு நடந்தது',
    'message.loading': 'சுமைகிறது...',
  },
  
  Kannada: {
    'auth.title': 'ಮತ್ತೆ ಸ್ವಾಗತ',
    'auth.createAccount': 'ಖಾತೆ ರಚಿಸಿ',
    'auth.signInSubtitle': 'ಮುಂದುವರೆಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ',
    'auth.signUpSubtitle': 'ಪ್ರಾರಂಭಿಸಲು ಸೈನ್ ಅಪ್ ಮಾಡಿ',
    'auth.signIn': 'ಸೈನ್ ಇನ್ ಮಾಡಿ',
    'auth.signUp': 'ಸೈನ್ ಅಪ್ ಮಾಡಿ',
    'auth.email': 'ಇಮೇಲ್',
    'auth.password': 'ಪಾಸ್‌ವರ್ಡ್',
    'auth.phone': 'ಫೋನ್ ಸಂಖ್ಯೆ',
    'auth.name': 'ಪೂರ್ಣ ಹೆಸರು',
    'auth.forgotPassword': 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತುಬಿದ್ದೀರಾ?',
    'auth.dontHaveAccount': 'ಖಾತೆ ಇಲ್ಲವೇ?',
    'auth.alreadyHaveAccount': 'ಈಗಾಗಲೆ ಖಾತೆ ಇದೆಯೇ?',
    'auth.rememberMe': 'ನನ್ನನ್ನು ನೆನಪಿಡಿ',
    
    'nav.home': 'ಮನೆ',
    'nav.jobs': 'ಉದ್ಯೋಗಗಳು',
    'nav.messages': 'ಸಂದೇಶಗಳು',
    'nav.chats': 'ಚಾಟ್‌ಗಳು',
    'nav.notifications': 'ಅಧಿಸೂಚನೆಗಳು',
    'nav.profile': 'ಪ್ರೊಫೈಲ್',
    'nav.settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'nav.about': 'ನಮ್ಮ ಬಗ್ಗೆ',
    'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'nav.postJob': 'ಉದ್ಯೋಗ ಪೋಸ್ಟ್ ಮಾಡಿ',
    'owner.manageJobs': 'ಉದ್ಯೋಗಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    'job.createJob': 'ಉದ್ಯೋಗ ರಚಿಸಿ',
    
    'common.save': 'ಉಳಿಸಿ',
    'common.cancel': 'ರದ್ದುಗೊಳಿಸಿ',
    'common.delete': 'ಅಳಿಸಿ',
    'common.edit': 'ಸಂಪಾದಿಸಿ',
    'common.loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    'common.error': 'ಲೋಪ',
    'common.success': 'ಯಶಸ್ವಿ',
    'common.back': 'ಹಿಂದೆ',
    'common.next': 'ಮುಂದೆ',
    'common.remember': 'ನೆನಪಿಡಿ',
    'common.submit': 'ಸಲ್ಲಿಸಿ',
    'common.logout': 'ಲಾಗ್‌ಅವುಟ್',
    'common.close': 'ಮುಚ್ಚಿ',
    'common.search': 'ಹುಡುಕಿ',
    'common.filter': 'ಶೋಧಿಸಿ',
    'common.apply': 'ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    'common.send': 'ಕಳುಹಿಸಿ',
    'common.message': 'ಸಂದೇಶ',
    'common.call': 'ಕರೆ ಮಾಡಿ',
    'common.continue': 'ಮುಂದುವರೆಸಿ',
    'common.skip': 'ಬಿಟ್ಟುಬಿಡಿ',
    'common.download': 'ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    'common.upload': 'ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    'common.change': 'ಬದಲಾಯಿಸಿ',
    'common.confirm': 'ಖಚಿತ ಮಾಡಿ',
    'common.yes': 'ಹೌದು',
    'common.no': 'ಇಲ್ಲ',
    'common.all': 'ಎಲ್ಲಾ',
    'common.more': 'ಹೆಚ್ಚು',
    'common.view': 'ವೀಕ್ಷಿಸಿ',
    'common.details': 'ವಿವರಗಳು',
    
    'jobs.findJobs': 'ಉದ್ಯೋಗಗಳನ್ನು ಹುಡುಕಿ',
    'jobs.applyNow': 'ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    'jobs.availableCredits': 'ಲಭ್ಯ ಸಾಲಗಳು',
    'jobs.applied': 'ಅರ್ಜಿ ಸಲ್ಲಿಸಿದೆ',
    
    'profile.myProfile': 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    'profile.verified': 'ಪರಿಶೀಲಿತ',
    
    'messages.messages': 'ಸಂದೇಶಗಳು',
    'messages.chats': 'ಚಾಟ್‌ಗಳು',
    'messages.sendMessage': 'ಸಂದೇಶ ಕಳುಹಿಸಿ',
    
    'notifications.title': 'ಅಧಿಸೂಚನೆಗಳು',
    'notifications.noNotifications': 'ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ',
    
    'settings.settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'settings.language': 'ಭಾಷೆ',
    'settings.logout': 'ಲಾಗ್‌ಅವುಟ್',
    
    'message.success': 'ಯಶಸ್ವಿ!',
    'message.error': 'ಏನಾದರೂ ತಪ್ಪಾಯಿತು',
    'message.loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
  },
  
  Gujarati: {
    'auth.title': 'પાછા આવીને સ્વાગત છે',
    'auth.createAccount': 'ખાતું બનાવો',
    'auth.signInSubtitle': 'ચાલુ રાખવા માટે સાઇન ઇન કરો',
    'auth.signUpSubtitle': 'શરુ કરવા માટે સાઇન અપ કરો',
    'auth.signIn': 'સાઇન ઇન કરો',
    'auth.signUp': 'સાઇન અપ કરો',
    'auth.email': 'ઈમેલ',
    'auth.password': 'પાસવર્ડ',
    'auth.phone': 'ફોન નંબર',
    'auth.name': 'સંપૂર્ણ નામ',
    'auth.forgotPassword': 'પાસવર્ડ ભૂલી ગયા?',
    'auth.dontHaveAccount': 'ખાતું નથી?',
    'auth.alreadyHaveAccount': 'પહેલાથી ખાતું છે?',
    'auth.rememberMe': 'મને યાદ રાખો',
    
    'nav.home': 'ઘર',
    'nav.jobs': 'નોકરીઓ',
    'nav.messages': 'સંદેશાઓ',
    'nav.chats': 'ચેટ્સ',
    'nav.notifications': 'સૂચનાઓ',
    'nav.profile': 'પ્રોફાઇલ',
    'nav.settings': 'સેટિંગ્સ',
    'nav.about': 'આપણા વિશે',
    
    'common.save': 'સુરક્ષિત કરો',
    'common.cancel': 'રદ્દ કરો',
    'common.delete': 'કાઢી નાખો',
    'common.edit': 'સંપાદિત કરો',
    'common.loading': 'લોડ થઈ રહ્યું છે...',
    'common.error': 'ભૂલ',
    'common.success': 'સફળતા',
    'common.back': 'પાછળ',
    'common.next': 'આગલું',
    'common.logout': 'લૉગઆઉટ',
    
    'jobs.findJobs': 'નોકરીઓ શોધો',
    'jobs.applyNow': 'અત્યારે અરજી કરો',
    
    'profile.myProfile': 'મારી પ્રોફાઇલ',
    'profile.verified': 'સત્યાપિત',
    
    'settings.settings': 'સેટિંગ્સ',
    'settings.language': 'ભાષા',
    'settings.logout': 'લૉગઆઉટ',
    
    'message.success': 'સફળતા!',
    'message.error': 'કંઈક ગણો તપાસ સમાપ્ત થયું',
    'message.loading': 'લોડ થઈ રહ્યું છે...',
  },
  
  Malayalam: {
    'auth.title': 'സ്വാഗതം ഫിരിയെത്തിയതിന്',
    'auth.createAccount': 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    'auth.signInSubtitle': 'തുടരുന്നതിന് സൈൻ ഇൻ ചെയ്യുക',
    'auth.signUpSubtitle': 'തുടങ്ങാൻ സൈൻ അപ്പ് ചെയ്യുക',
    'auth.signIn': 'സൈൻ ഇൻ ചെയ്യുക',
    'auth.signUp': 'സൈൻ അപ്പ് ചെയ്യുക',
    'auth.email': 'ഇമെയിൽ',
    'auth.password': 'പാസ്‌വേഡ്',
    'auth.phone': 'ഫോൻ നമ്പർ',
    'auth.name': 'പൂർണ്ണ നാമം',
    'auth.forgotPassword': 'പാസ്‌വേഡ് മറന്നുവോ?',
    'auth.dontHaveAccount': 'അക്കൗണ്ട് ഇല്ലയോ?',
    'auth.alreadyHaveAccount': 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?',
    'auth.rememberMe': 'എന്നെ ഓർക്കുക',
    
    'nav.home': 'ഹോം',
    'nav.jobs': 'ജോലികൾ',
    'nav.messages': 'സന്ദേശങ്ങൾ',
    'nav.chats': 'ചാറ്റുകൾ',
    'nav.notifications': 'അറിയിപ്പുകൾ',
    'nav.profile': 'പ്രൊഫൈൽ',
    'nav.settings': 'സെറ്റിംഗ്‌സ്',
    'nav.about': 'ഞങ്ങൾ എങ്ങനെയോ',
    
    'common.save': 'സംരക്ഷിക്കുക',
    'common.cancel': 'റദ്ദാക്കുക',
    'common.delete': 'ഇല്ലാതാക്കുക',
    'common.edit': 'തിരുത്തുക',
    'common.loading': 'ലോഡ് ചെയ്യുന്നു...',
    'common.error': 'പിശക്',
    'common.success': 'വിജയം',
    'common.back': 'പിന്നിലേക്ക്',
    'common.next': 'അടുത്തത്',
    'common.logout': 'ലോഗൗട്ട്',
    
    'jobs.findJobs': 'ജോലികൾ കണ്ടെത്തുക',
    'jobs.applyNow': 'ഇപ്പോൾ അപേക്ഷിക്കുക',
    
    'profile.myProfile': 'എന്റെ പ്രൊഫൈൽ',
    'profile.verified': 'പരിശോധിച്ച',
    
    'settings.settings': 'സെറ്റിംഗ്‌സ്',
    'settings.language': 'ഭാഷ',
    'settings.logout': 'ലോഗൗട്ട്',
    
    'message.success': 'വിജയം!',
    'message.error': 'എന്തോ തെറ്റായി',
    'message.loading': 'ലോഡ് ചെയ്യുന്നു...',
  },
  
  Marathi: {
    'auth.title': 'पुन्हा स्वागत आहे',
    'auth.createAccount': 'खाते तयार करा',
    'auth.signInSubtitle': 'सुरू ठेवण्यासाठी साइन इन करा',
    'auth.signUpSubtitle': 'सुरुवात करण्यासाठी साइन अप करा',
    'auth.signIn': 'साइन इन करा',
    'auth.signUp': 'साइन अप करा',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'auth.phone': 'फोन नंबर',
    'auth.name': 'पूर्ण नाव',
    'auth.forgotPassword': 'पासवर्ड विसरलात?',
    'auth.dontHaveAccount': 'खाते नाही का?',
    'auth.alreadyHaveAccount': 'आधीच खाते आहे का?',
    'auth.rememberMe': 'मला लक्षात ठेवा',
    
    'nav.home': 'घर',
    'nav.jobs': 'नोकरी',
    'nav.messages': 'संदेश',
    'nav.chats': 'चॅट्स',
    'nav.notifications': 'सूचना',
    'nav.profile': 'प्रोफाइल',
    'nav.settings': 'सेटिंग्‍ज',
    'nav.about': 'आमच्या बद्दल',
    
    'common.save': 'सेव करा',
    'common.cancel': 'रद्द करा',
    'common.delete': 'हटवा',
    'common.edit': 'संपादित करा',
    'common.loading': 'लोड होत आहे...',
    'common.error': 'त्रुटी',
    'common.success': 'यश',
    'common.back': 'परत',
    'common.next': 'पुढील',
    'common.logout': 'लॉगआउट',
    
    'jobs.findJobs': 'नोकरी शोधा',
    'jobs.applyNow': 'आता अर्ज करा',
    
    'profile.myProfile': 'माझी प्रोफाइल',
    'profile.verified': 'सत्यापित',
    
    'settings.settings': 'सेटिंग्‍ज',
    'settings.language': 'भाषा',
    'settings.logout': 'लॉगआउट',
    
    'message.success': 'यश!',
    'message.error': 'काहीतरी गंमत झाले',
    'message.loading': 'लोड होत आहे...',
  },
  
  Urdu: {
    'auth.title': 'واپسی میں خوش آمدید',
    'auth.createAccount': 'اکاؤنٹ بنائیں',
    'auth.signInSubtitle': 'جاری رکھنے کے لیے سائن ان کریں',
    'auth.signUpSubtitle': 'شروع کرنے کے لیے سائن اپ کریں',
    'auth.signIn': 'سائن ان کریں',
    'auth.signUp': 'سائن اپ کریں',
    'auth.email': 'ای میل',
    'auth.password': 'پاس ورڈ',
    'auth.phone': 'فون نمبر',
    'auth.name': 'مکمل نام',
    'auth.forgotPassword': 'پاس ورڈ بھول گئے؟',
    'auth.dontHaveAccount': 'اکاؤنٹ نہیں ہے؟',
    'auth.alreadyHaveAccount': 'پہلے سے اکاؤنٹ ہے؟',
    'auth.rememberMe': 'مجھے یاد رکھیں',
    
    'nav.home': 'گھر',
    'nav.jobs': 'ملازمت',
    'nav.messages': 'پیغامات',
    'nav.chats': 'بات چیت',
    'nav.notifications': 'اطلاعات',
    'nav.profile': 'پروفائل',
    'nav.settings': 'ترتیبات',
    'nav.about': 'ہمارے بارے میں',
    
    'common.save': 'محفوظ کریں',
    'common.cancel': 'منسوخ کریں',
    'common.delete': 'حذف کریں',
    'common.edit': 'ترمیم کریں',
    'common.loading': 'لوڈ ہو رہا ہے...',
    'common.error': 'خرابی',
    'common.success': 'کامیابی',
    'common.back': 'پیچھے',
    'common.next': 'آگے',
    'common.logout': 'لاگ آؤٹ',
    
    'jobs.findJobs': 'ملازمت تلاش کریں',
    'jobs.applyNow': 'ابھی درخواست دیں',
    
    'profile.myProfile': 'میری پروفائل',
    'profile.verified': 'تصدیق شدہ',
    
    'settings.settings': 'ترتیبات',
    'settings.language': 'زبان',
    'settings.logout': 'لاگ آؤٹ',
    
    'message.success': 'کامیابی!',
    'message.error': 'کچھ غلط ہو گیا',
    'message.loading': 'لوڈ ہو رہا ہے...',
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [currentLanguage, setLanguage] = useState<Language>('English')

  useEffect(() => {
    const saved = localStorage.getItem('language')
    if (saved && (Object.keys(translations) as Language[]).includes(saved as Language)) {
      setLanguage(saved as Language)
    }
  }, [])

  const t = (key: string): string => {
    const lang = translations[currentLanguage]
    return lang[key as keyof typeof lang] || translations.English[key as keyof typeof translations.English] || key
  }

  useEffect(() => {
    localStorage.setItem('language', currentLanguage)
  }, [currentLanguage])

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
